ciha_dict = {
    'ANO_CMPT': {'type': 'CHAR (4)', 'description': 'Ano de competência da CIH, formato AA'},
    'MES_CMPT': {'type': 'CHAR (2)', 'description': 'Mês de competência da CIH, formato MM'},
    'ESPEC': {'type': 'CHAR (2)', 'description': '(Vazio)'},
    'CGC_HOSP': {'type': 'CHAR (14)', 'description': 'CNPJ do Estabelecimento de Saúde'},
    'MUNIC_RES': {'type': 'CHAR (6)', 'description': 'Município de residência'},
    'NASC': {'type': 'CHAR (8)', 'description': 'Data de nascimento do paciente'},
    'SEXO': {'type': 'CHAR (1)', 'description': 'Sexo do paciente'},
    'UTI_MES_TO': {'type': 'CHAR (3)', 'description': '(zerado)'},
    'UTI_INT_TO': {'type': 'CHAR (3)', 'description': 'Total de dias de UTI intermediária durante a internação'},
    'PROC_REA': {'type': 'CHAR (10)', 'description': 'Procedimento realizado'},
    'QT_PROC': {'type': 'CHAR (6)', 'description': 'Quantidade de procedimento'},
    'DT_ATEND': {'type': 'CHAR (8)', 'description': 'Data do atendimento, formato AAAAMMDD'},
    'DT_SAIDA': {'type': 'CHAR (8)', 'description': 'Data de saída, formato AAAAMMDD'},
    'DIAG_PRINC': {'type': 'CHAR (4)', 'description': 'Diagnóstico principal, segundo a CID-10'},
    'DIAG_SECUN': {'type': 'CHAR (4)', 'description': 'Diagnóstico secundário, segundo a CID-10'},
    'COBRANCA': {'type': 'CHAR (2)', 'description': 'Motivo da cobrança'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Natureza da relação do hospital com o SUS'},
    'GESTAO': {'type': 'CHAR (1)', 'description': 'Indica o tipo de gestão do hospital'},
    'MUNIC_MOV': {'type': 'CHAR (6)', 'description': 'Código do município onde se localiza o hospital'},
    'COD_IDADE': {'type': 'CHAR (1)', 'description': 'Unidade de medida da idade: 0 – ignorada, 2 – dias, 3 – meses, 4 – anos, 5 – anos (mais de 100)'},
    'IDADE': {'type': 'CHAR (2)', 'description': 'Idade, na unidade do campo COD_IDADE'},
    'DIAS_PERM': {'type': 'CHAR (5)', 'description': 'Dias de permanência'},
    'MORTE': {'type': 'CHAR (1)', 'description': 'Indica se o paciente teve saída com morte: 0– Não 1 – Sim'},
    'NACIONAL': {'type': 'CHAR (3)', 'description': '(Vazio)'},
    'CAR_INT': {'type': 'CHAR (2)', 'description': '(Vazio)'},
    'HOMONIMO': {'type': 'CHAR (1)', 'description': '(Vazio)'},
    'CNES': {'type': 'CHAR (7)', 'description': 'Código CNES do estabelecimento'},
    'FONTE': {'type': 'CHAR (2)', 'description': 'Fonte da remuneração'},
    'MODALIDADE': {'type': 'CHAR (2)', 'description': 'Modalidade do atendimento'}
}