lt_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (6)', 'description': 'Código do município do estabelecimento UF+MUNIC (sem dígito)'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde'},
    'DISTRSAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Código do distrito administrativo'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física 3-Jurídica'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF do Estabelecimento, caso pessoa física OU CNPJ, caso pessoa jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência: 1-Individual 3-Mantida'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do Estabelecimento'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de fluxo da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade (Estabelecimento)'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TERCEIRO': {'type': 'CHAR (1)', 'description': 'O estabelecimento é terceiro: 1-Sim 0-Não'},
    'TP_LEITO': {'type': 'CHAR (2)', 'description': 'Tipo do LEITO'},
    'CODLEITO': {'type': 'CHAR (2)', 'description': 'Especialidade do LEITO'},
    'QT_EXIST': {'type': 'NUMERIC (4)', 'description': 'Quantidade de leitos existentes'},
    'QT_CONTR': {'type': 'NUMERIC (4)', 'description': 'Quantidade de leitos contratados'},
    'QT_SUS': {'type': 'NUMERIC (4)', 'description': 'Quantidade de leitos para o SUS'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'}
}


pf_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (6)', 'description': 'Código do município do estabelecimento UF + MUNIC (sem dígito)'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde'},
    'DISTRASAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Código do distrito administrativo'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física 3-Jurídica'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF do Estabelecimento, caso pessoa física ou CNPJ, caso pessoa jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência, onde: 1-Individual 3-Mantida'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do estabelecimento'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de fluxo da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade (estabelecimento)'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TERCEIRO': {'type': 'CHAR (2)', 'description': 'O estabelecimento é terceiro: 1-Sim 0-Não 2-não'},
    'CPF_PROF': {'type': 'CHAR (11)', 'description': 'CPF do Profissional ou caso “99999999999” caso não seja preenchido.'},
    'CPF_UNICO': {'type': 'CHAR (6)', 'description': 'Contador de CPF ÚNICO do Profissional (O preenchimento deste campo acontece somente uma vez por chave - única- CPF) Nos casos em que o CPF for 99999999999, o CPFUNICO sempre deve ser "1".'},
    'CBO': {'type': 'CHAR (6)', 'description': 'Código da especialidade do profissional'},
    'CBO_UNICO': {'type': 'CHAR (2)', 'description': 'Registro único do Código da especialidade do profissional (este registro acontece somente uma vez por chave única CPF + CBO)'},
    'NOMEPROF': {'type': 'CHAR (60)', 'description': 'Nome do profissional'},
    'CNS_PROF': {'type': 'CHAR (15)', 'description': 'CNS do profissional ou “999999999999999” caso não seja preenchido.'},
    'CONSELHO': {'type': 'CHAR (2)', 'description': 'Código do conselho de classe'},
    'REGISTRO': {'type': 'CHAR (13)', 'description': 'Número do registro no conselho de classe'},
    'VINCULAC': {'type': 'CHAR (6)', 'description': 'Vínculo empregatício com o estabelecimento:'},
    'VINCUL_C': {'type': 'CHAR (1)', 'description': 'Vínculo empregatício com o estabelecimento: Contratado SUS'},
    'VINCUL_A': {'type': 'CHAR (1)', 'description': 'Vínculo empregatício com o estabelecimento: Autônomo SUS'},
    'VINCUL_N': {'type': 'CHAR (1)', 'description': 'Vínculo empregatício com o estabelecimento: Vínculo não identificado (registros de profissionais não SUS e outras situações anômalas)'},
    'PROF_SUS': {'type': 'CHAR (1)', 'description': 'Caracterização do PROFISSIONAL que realiza ATENDIMENTO SUS'},
    'PROFNSUS': {'type': 'CHAR (1)', 'description': 'Caracterização do PROFISSIONAL que realiza ATENDIMENTO NÃO SUS'},
    'HORAOUTR': {'type': 'CHAR (3)', 'description': 'Carga horária não ambulatorial, nem hospitalar'},
    'HORAHOSP': {'type': 'CHAR (3)', 'description': 'Carga horária HOSPITALAR'},
    'HORA_AMB': {'type': 'CHAR (3)', 'description': 'Carga horária AMBULATORIAL'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'},
    'UFMUNRES': {'type': 'CHAR (8)', 'description': 'Código da UF + município de residência do profissional (sem dígito)'},
    'NAT_JUR': {'type': 'CHAR (4)', 'description': 'Natureza Jurídica'}
}


dc_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (7)', 'description': 'Código do município do estabelecimento: UF + MUNIC (sem dígito)'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF do estabelecimento, caso pessoa física ou CNPJ, caso pessoa jurídica'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física 3-Jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência, onde: 1-Individual 3-Mantida'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do estabelecimento.'},
    'COD_IR': {'type': 'CHAR (2)', 'description': 'Indica o tipo de retenção de tributos da mantenedora'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde NOAS'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde NOAS'},
    'DISTRSAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Inicialmente chamado Distrito Administrativo, atualmente Código do Módulo Assistencial conforme tabela local, em conformidade com o Plano Diretor de Regionalização do Estado/Município.'},
    'VINC_SUS': {'type': 'CHAR (1)', 'description': 'Vínculo com SUS: 1-Sim 0-Não'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino/pesquisa'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de FLUXO da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade (estabelecimento)'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TPPREST': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'S_HBSAGP': {'type': 'NUMBER (2)', 'description': 'Quantidade de salas HBsAG+'},
    'S_HBSAGN': {'type': 'NUMBER (2)', 'description': 'Quantidade de salas HBsAG-'},
    'S_DPI': {'type': 'NUMBER (2)', 'description': 'Quantidade de salas DPI'},
    'S_DPAC': {'type': 'NUMBER (2)', 'description': 'Quantidade de salas DPAC'},
    'S_REAGP': {'type': 'NUMBER (2)', 'description': 'Quantidade de salas de reuso de HBsAG+'},
    'S_REAGN': {'type': 'NUMBER (2)', 'description': 'Quantidade de salas de reuso de HBsAG-'},
    'S_REHCV': {'type': 'NUMBER (2)', 'description': 'Quantidade de Salas de reuso de HCV+'},
    'MAQ_PROP': {'type': 'NUMBER (2)', 'description': 'Quantidade de máquinas de proporção'},
    'MAQ_OUTR': {'type': 'NUMBER (2)', 'description': 'Quantidade de outras máquinas'},
    'F_AREIA': {'type': 'CHAR (1)', 'description': 'Indica se faz tratamento de água com filtro de areia, onde: 1-Sim 0-Não'},
    'F_CARVAO': {'type': 'CHAR (1)', 'description': 'Indica se faz tratamento de água com filtro de carvão, onde: 1-Sim 0-Não'},
    'ABRANDAD': {'type': 'CHAR (1)', 'description': 'Indica se faz tratamento de água com abrandador, onde: 1-Sim 0-Não'},
    'DEIONIZA': {'type': 'CHAR (1)', 'description': 'Indica se faz tratamento de água com deionizador, onde: 1-Sim 0-Não'},
    'OSMOSE_R': {'type': 'CHAR (1)', 'description': 'Indica se faz tratamento de água com máquina de osmose reversa, onde: 1-Sim 0-Não'},
    'OUT_TRAT': {'type': 'CHAR (1)', 'description': 'Indica se faz tratamento de água com outros tipos de equipamento, onde: 1-Sim 0-Não'},
    'CNS_NEFR': {'type': 'CHAR (15)', 'description': 'CNS do MÉDICO NEFROLOGISTA RESPONSÀVEL'},
    'DIALISE': {'type': 'CHAR (1)', 'description': 'Indica a existência de algum REQUISITO DE DIÁLISE para este CNES, onde: 1-Sim 0-Não'},
    'SIMUL_RD': {'type': 'NUMERIC (2)', 'description': 'Quantidade de salas simulação – (Radioterapia)'},
    'PLANJ_RD': {'type': 'NUMERIC (2)', 'description': 'Quantidade de salas de Planejamento - (Radioterapia)'},
    'ARMAZ_FT': {'type': 'NUMERIC (2)', 'description': 'Número de salas de armazenamento de fontes - (Radioterapia)'},
    'CONF_MAS': {'type': 'NUMERIC (2)', 'description': 'Número de salas confecção masc. - (Radioterapia)'},
    'SALA_MOL': {'type': 'NUMERIC (2)', 'description': 'Número de salas de salas de molde - (Radioterapia)'},
    'BLOCOPER': {'type': 'NUMERIC (2)', 'description': 'Número de salas de bloco personalizado - (Radioterapia)'},
    'S_ARMAZE': {'type': 'NUMERIC (2)', 'description': 'Número de salas de armazenagem'},
    'S_PREPAR': {'type': 'NUMERIC (2)', 'description': 'Número de salas de preparo'},
    'S_QCDURA': {'type': 'NUMERIC (2)', 'description': 'Salas/Equipamentos de Quimio Curta duração'},
    'S_QLDURA': {'type': 'NUMERIC (2)', 'description': 'Salas/Equipamentos de Quimio de Longa Duração'},
    'S_CPFLUX': {'type': 'NUMERIC (2)', 'description': 'Salas/Equipamentos de Capela Fluxo Laminar'},
    'S_SIMULA': {'type': 'NUMERIC (2)', 'description': 'Quantidade de Simuladores'},
    'S_ACELL6': {'type': 'NUMERIC (2)', 'description': 'Quantidade de Acelerador Linear até 6 MeV'},
    'S_ALSEME': {'type': 'NUMERIC (2)', 'description': 'Quantidade de Acelerador Linear maior 6 MeV sem elétrons'},
    'S_ALCOME': {'type': 'NUMERIC (2)', 'description': 'Quantidade de acelerador linear maior 6 MeV com elétrons'},
    'ORTV1050': {'type': 'NUMERIC (2)', 'description': 'Quantidade de Equipamentos de Ortovoltagem 10-50 KV'},
    'ORV50150': {'type': 'NUMERIC (2)', 'description': 'Quantidade de Equipamentos de Ortovoltagem 50-150 KV'},
    'OV150500': {'type': 'NUMERIC (2)', 'description': 'Quantidade de Equipamentos de Ortovoltagem 150-500 KV'},
    'UN_COBAL': {'type': 'NUMERIC (2)', 'description': 'Quantidade de Unidade de Cobalto'},
    'EQBRBAIX': {'type': 'NUMERIC (2)', 'description': 'Quantidade de Equipamentos de Braquiterapia Baixa'},
    'EQBRMEDI': {'type': 'NUMERIC (2)', 'description': 'Quantidade de Equipamentos de Braquiterapia Média'},
    'EQBRALTA': {'type': 'NUMERIC (2)', 'description': 'Quantidade de Equipamentos de Braquiterapia Alta'},
    'EQ_MAREA': {'type': 'NUMERIC (2)', 'description': 'Quantidade de Monitor de Área'},
    'EQ_MINDI': {'type': 'NUMERIC (2)', 'description': 'Quantidade de Monitor Individual'},
    'EQSISPLN': {'type': 'NUMERIC (2)', 'description': 'Quantidade de sistema de Computação para Planejamento'},
    'EQDOSCLI': {'type': 'NUMERIC (2)', 'description': 'Quantidade de dosímetro clínico'},
    'EQFONSEL': {'type': 'NUMERIC (2)', 'description': 'Quantidade de fontes seladas'},
    'CNS_ADM': {'type': 'CHAR (15)', 'description': 'CNS do médico responsável – ADMINISTRADOR OU RESPONSÁVEL TÉCNICO'},
    'CNS_OPlD': {'type': 'CHAR (15)', 'description': 'CNS do médico responsável - ONCOLOGISTA PEDIÁTRICO'},
    'CNS_CONC': {'type': 'CHAR (15)', 'description': 'CNS do médico responsável - por CIRURGIA ONCOLÓGICA'},
    'CNS_OCLIN': {'type': 'CHAR (15)', 'description': 'CNS do médico responsável - ONCOLOGISTA CLÍNICO'},
    'CNS_MRAD': {'type': 'CHAR (15)', 'description': 'CNS do médico responsável - RADIOTERAPEUTA'},
    'CNS_FNUC': {'type': 'CHAR (15)', 'description': 'CNS do médico responsável - FÍSICO NUCLEAR'},
    'QUIMRADI': {'type': 'CHAR (1)', 'description': 'Indica a existência de algum REQUISITO DE QUÍMIO/RÁDIO para este CNES, onde: 1-Sim 0-Não'},
    'S_RECEPC': {'type': 'NUMERIC (3)', 'description': 'Número de salas de recepção'},
    'S_TRIHMT': {'type': 'NUMERIC (3)', 'description': 'Número de salas de triagem hematológica'},
    'S_TRICLI': {'type': 'NUMERIC (3)', 'description': 'Número de salas de triagem clínica'},
    'S_COLETA': {'type': 'NUMERIC (3)', 'description': 'Número de salas de coleta'},
    'S_AFERES': {'type': 'NUMERIC (3)', 'description': 'Número de salas de aférese'},
    'S_PREEST': {'type': 'NUMERIC (3)', 'description': 'Número de salas de pré-estoque'},
    'S_PROCES': {'type': 'NUMERIC (3)', 'description': 'Número de salas de processamento'},
    'S_ESTOQU': {'type': 'NUMERIC (3)', 'description': 'Número de salas de estoque'},
    'S_DISTRI': {'type': 'NUMERIC (3)', 'description': 'Número de salas de distribuição'},
    'S_SOROLO': {'type': 'NUMERIC (3)', 'description': 'Número de salas de sorologia'},
    'S_IMUNOH': {'type': 'NUMERIC (3)', 'description': 'Número de salas de imunohematologia'},
    'S_PRETRA': {'type': 'NUMERIC (3)', 'description': 'Número de salas pré-transfusionais'},
    'S_HEMOST': {'type': 'NUMERIC (3)', 'description': 'Número de salas hemostasia'},
    'S_CONTRQ': {'type': 'NUMERIC (3)', 'description': 'Número de salas de controle de qualidade'},
    'S_BIOMOL': {'type': 'NUMERIC (3)', 'description': 'Número de salas de biologia molecular'},
    'S_IMUNFE': {'type': 'NUMERIC (3)', 'description': 'Número de salas de imunofenotipágem'},
    'S_TRANSF': {'type': 'NUMERIC (3)', 'description': 'Número de salas de transfusão'},
    'S_SGDOAD': {'type': 'NUMERIC (3)', 'description': 'Número de salas seguimento doador'},
    'QT_CADRE': {'type': 'NUMERIC (3)', 'description': 'Quantidade de cadeiras reclináveis'},
    'QT_CENRE': {'type': 'NUMERIC (3)', 'description': 'Quantidade de centrífugas refrigeradas'},
    'QT_REFSA': {'type': 'NUMERIC (3)', 'description': 'Quantidade de refrigeradores para guarda de sangue'},
    'QT_CONRA': {'type': 'NUMERIC (3)', 'description': 'Quantidade de congeladores rápidos'},
    'QT_EXTPL': {'type': 'NUMERIC (3)', 'description': 'Quantidade de extratores automáticos de plasma'},
    'QT_FRE18': {'type': 'NUMERIC (3)', 'description': 'Quantidade de freezers –18ºC'},
    'QT_FRE30': {'type': 'NUMERIC (3)', 'description': 'Quantidade de freezers -30ºC'},
    'QT_AGIPL': {'type': 'NUMERIC (3)', 'description': 'Quantidade de agitadores de plaquetas'},
    'QT_SELAD': {'type': 'NUMERIC (3)', 'description': 'Quantidade de seladoras'},
    'QT_IRRHE': {'type': 'NUMERIC (3)', 'description': 'Quantidade de irradiadores de hemocomponentes'},
    'QT_AGLTN': {'type': 'NUMERIC (3)', 'description': 'Quantidade de aglutinoscópio'},
    'QT_MAQAF': {'type': 'NUMERIC (3)', 'description': 'Quantidade de máquinas de aférese'},
    'QT_REFRE': {'type': 'NUMERIC (3)', 'description': 'Quantidade de refrigeradores para guarda de reagentes'},
    'QT_REFAS': {'type': 'NUMERIC (3)', 'description': 'Quantidade de refrigeradores para guarda de amostras de sangue'},
    'QT_CAPFL': {'type': 'NUMERIC (3)', 'description': 'Quantidade de capelas fluxo laminar'},
    'CNS_HMTR': {'type': 'CHAR (15)', 'description': 'CNS do médico responsável - HEMOTERAPEUTA'},
    'CNS_HMTL': {'type': 'CHAR (15)', 'description': 'CNS do médico responsável - HEMATOLOGISTA'},
    'CNS_CRES': {'type': 'CHAR (15)', 'description': 'CNS do médico capacitado RESPONSÀVEL'},
    'CNS_RTEC': {'type': 'CHAR (15)', 'description': 'CNS do responsável TÉCNICO / SOROLOGIA'},
    'HEMOTERA': {'type': 'CHAR (1)', 'description': 'Indica a existência de algum REQUISITO DE HEMOTERAPIA para este CNES, onde: 1-Sim 0-Não'},
    'AP01CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio SUS, onde: 1-Sim 0-Não'},
    'AP01CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PARTICULAR, onde: 1-Sim 0-Não'},
    'AP01CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PLANO de SAUDE PUBLICO, onde: 1-Sim 0-Não'},
    'AP01CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PLANO de SAUDE PRIVADO, onde: 1-Sim 0-Não'},
    'AP01CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PLANO-SEGURO PROPRIO, onde: 1-Sim 0-Não'},
    'AP01CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PLANO-SEGURO TERCEIRO, onde: 1-Sim 0-Não'},
    'AP02CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio SUS, onde: 1-Sim 0-Não'},
    'AP02CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PARTICULAR, onde: 1-Sim 0-Não'},
    'AP02CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PLANO de SAUDE PUBLICO, onde: 1-Sim 0-Não'},
    'AP02CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PLANO de SAUDE PRIVADO, onde: 1-Sim 0-Não'},
    'AP02CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PLANOSEGURO PROPRIO, onde: 1-Sim 0-Não'},
    'AP02CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PLANOSEGURO TERCEIRO, onde: 1-Sim 0-Não'},
    'AP03CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/Convenio SUS, onde: 1-Sim 0-Não'},
    'AP03CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/Convenio PARTICULAR, onde: 1-Sim 0-Não'},
    'AP03CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/Convenio PLANO de SAUDE PUBLICO, onde: 1-Sim 0-Não'},
    'AP03CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/Convenio PLANO de SAUDE PRIVADO, onde: 1-Sim 0-Não'},
    'AP03CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/Convenio PLANO-SEGURO PROPRIO, onde: 1-Sim 0-Não'},
    'AP03CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/Convenio PLANO-SEGURO TERCEIRO, onde: 1-Sim 0-Não'},
    'AP04CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio SUS, onde: 1-Sim 0-Não'},
    'AP04CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio PARTICULAR, onde: 1-Sim 0-Não'},
    'AP04CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio PLANO de SAUDE PUBLICO, onde: 1-Sim 0-Não'},
    'AP04CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio PLANO de SAUDE PRIVADO, onde: 1-Sim 0-Não'},
    'AP04CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio PLANO-SEGURO PROPRIO, onde: 1-Sim 0-Não'},
    'AP04CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio PLANO-SEGURO TERCEIRO, onde: 1-Sim 0-Não'},
    'AP05CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio SUS, onde: 1-Sim 0-Não'},
    'AP05CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PARTICULAR, onde: 1-Sim 0-Não'},
    'AP05CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PLANO de SAUDE PUBLICO, onde: 1-Sim 0-Não'},
    'AP05CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PLANO de SAUDE PRIVADO, onde: 1-Sim 0-Não'},
    'AP05CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PLANO-SEGURO PROPRIO, onde: 1-Sim 0-Não'},
    'AP05CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PLANO-SEGURO TERCEIRO, onde: 1-Sim 0-Não'},
    'AP06CV01': {'type': 'CHAR (1)', 'description': ' Atendimento prestado VIGILANCIA EM SAUDE/Convenio SUS, onde: 1-Sim 0-Não'},
    'AP06CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PARTICULAR, onde: 1-Sim 0-Não'},
    'AP06CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PLANO de SAUDE PUBLICO, onde: 1-Sim 0-Não'},
    'AP06CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PLANO de SAUDE PRIVADO, onde: 1-Sim 0-Não'},
    'AP06CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PLANO-SEGURO PROPRIO, onde: 1-Sim 0-Não'},
    'AP06CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PLANO-SEGURO TERCEIRO, onde: 1-Sim 0-Não'},
    'AP07CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio SUS, onde: 1-Sim 0-Não'},
    'AP07CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PARTICULAR, onde: 1-Sim 0-Não'},
    'AP07CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PLANO de SAUDE PUBLICO, onde: 1-Sim 0-Não'},
    'AP07CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PLANO de SAUDE PRIVADO, onde: 1-Sim 0-Não'},
    'AP07CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PLANO-SEGURO PROPRIO, onde: 1-Sim 0-Não'},
    'AP07CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PLANO-SEGURO TERCEIRO, onde: 1-Sim 0-Não'},
    'ATEND_PR': {'type': 'CHAR (1)', 'description': 'Indica a existência de algum atendimento prestado para este CNES, onde: 1-sim / 0-não'},
    'GESPRG3E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão do programa é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG3M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão do programa é MUNICIPAL, onde: 1-sim 0-não'},
    'GESPRG4E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ALTA COMPLEXIDADE do Nível de Atenção AMBULATORIAL é ESTADUAL, onde: 1-Sim 0-Não'},
    'GESPRG4M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ALTA COMPLEXIDADE do Nível de Atenção AMBULATORIAL é MUNICIPAL, onde: 1-Sim 0-Não'},
    'GESPRG6E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ALTA COMPLEXIDADE do Nível de Atenção HOSPITALAR é ESTADUAL, onde: 1-Sim 0-Não'},
    'GESPRG6M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ALTA COMPLEXIDADE do Nível de Atenção HOSPITALAR é MUNICIPAL, onde: 1-Sim 0-Não'},
    'NIVATE_A': {'type': 'CHAR (1)', 'description': 'Indica a existência de Nível de Atenção AMBULATORIAL, de gestão Municipal/Estadual, para este CNES, onde: 1-sim 0-não'},
    'NIVATE_H': {'type': 'CHAR (1)', 'description': 'Indica a existência de Nível de Atenção HOSPITALAR, de gestão Municipal/Estadual, para este CNES, onde: 1-sim 0-não'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'},
    'NAT_JUR': {'type': 'CHAR (4)', 'description': 'Natureza Jurídica'}
}


ee_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (6)', 'description': 'Código do município do estabelecimento UF+ MUNIC (sem dígito)'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde'},
    'DISTRSAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Código do distrito administrativo'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física 3-Jurídica'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF do Estabelecimento, caso pessoa física OU CNPJ, caso pessoa jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência: 1-Individual 3-Mantida'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do Estabelecimento'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de fluxo da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade (Estabelecimento)'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TERCEIRO': {'type': 'CHAR (1)', 'description': 'O estabelecimento é terceiro: 1-Sim 0-Não 2-não'},
    'COD_CEP': {'type': 'CHAR (8)', 'description': 'CEP do estabelecimento'},
    'VINC_SUS': {'type': 'CHAR (2)', 'description': 'Vínculo com SUS: 1-Sim 0-Não'},
    'TP_PREST': {'type': 'CHAR(2)', 'description': 'Tipo de Prestador'},
    'SGRUPHAB': {'type': 'CHAR(4)', 'description': 'Código da habilitação'},
    'CMPT_INI': {'type': 'CHAR(6)', 'description': 'Competência inicial'},
    'CMPT_FIM': {'type': 'CHAR(6)', 'description': 'Competência final'},
    'DTPORTAR': {'type': 'CHAR (10)', 'description': 'Data da portaria'},
    'PORTARIA': {'type': 'CHAR (50)', 'description': 'Portaria'},
    'MAPORTAR': {'type': 'CHAR (6)', 'description': 'Campo DT_PORTARIA formatado como AAAAMM'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'},
    'NAT_JUR': {'type': 'CHAR (4)', 'description': 'Natureza Jurídica'}
}


ef_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (6)', 'description': 'Código do município do estabelecimento UF+ MUNIC (sem dígito)'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde'},
    'DISTRSAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Código do distrito administrativo'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física 3-Jurídica'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF do Estabelecimento, caso pessoa física OU CNPJ, caso pessoa jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência: 1-Individual 3-Mantida'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do Estabelecimento'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de fluxo da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade (Estabelecimento)'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TERCEIRO': {'type': 'CHAR (1)', 'description': 'O estabelecimento é terceiro: 1-Sim 0-Não 2-não'},
    'COD_CEP': {'type': 'CHAR (8)', 'description': 'CEP do estabelecimento'},
    'VINC_SUS': {'type': 'CHAR (2)', 'description': 'Vínculo com SUS: 1-Sim 0-Não'},
    'TP_PREST': {'type': 'CHAR(2)', 'description': 'Tipo de Prestador'},
    'SGRUPHAB': {'type': 'CHAR(4)', 'description': 'Código da habilitação'},
    'CMPT_INI': {'type': 'CHAR(6)', 'description': 'Competência inicial'},
    'CMPT_FIM': {'type': 'CHAR(6)', 'description': 'Competência final'},
    'DTPORTAR': {'type': 'CHAR (10)', 'description': 'Data da portaria'},
    'PORTARIA': {'type': 'CHAR (50)', 'description': 'Portaria'},
    'MAPORTAR': {'type': 'CHAR (6)', 'description': 'Campo DT_PORTARIA formatado como AAAAMM'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'},
    'NAT_JUR': {'type': 'CHAR (6)', 'description': 'Natureza Jurídica'}
}


ep_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (7)', 'description': 'Código do município do estabelecimento: UF + MUNIC (sem dígito)'},
    'COD_CEP': {'type': 'CHAR (8)', 'description': 'Código do CEP do estabelecimento'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF do estabelecimento, caso pessoa física ou CNPJ, caso pessoa jurídica'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física 3-Jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência, onde: 1-Individual 3-Mantida'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do estabelecimento.'},
    'COD_IR': {'type': 'CHAR (2)', 'description': 'Indica o tipo de retenção de tributos da mantenedora'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde NOAS'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde NOAS'},
    'DISTRSAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Inicialmente chamado Distrito Administrativo, atualmente Código do Módulo Assistencial conforme tabela local, em conformidade com o Plano Diretor de Regionalização do Estado/Município.'},
    'VINC_SUS': {'type': 'CHAR (1)', 'description': 'Vínculo com SUS: 1-Sim 0-Não'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino/pesquisa'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de FLUXO da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade (estabelecimento)'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TERCEIRO': {'type': 'CHAR (1)', 'description': 'O estabelecimento é terceiro: 1-Sim 0-Não'},
    'TP_PREST': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'GESPRG1E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ATENÇÃO BÁSICA do Nível de Atenção AMBULATORIAL é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG1M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ATENÇÃO BÁSICA do Nível de Atenção AMBULATORIAL é MUNICIPAL, onde: 1-sim 0-não'},
    'GESPRG2E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade MÉDIA COMPLEXIDADE do Nível de Atenção AMBULATORIAL é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG2M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade MÉDIA COMPLEXIDADE do Nível de Atenção AMBULATORIAL é MUNICIPAL, onde: 1-sim 0-não'},
    'GESPRG4E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ALTA COMPLEXIDADE do Nível de Atenção AMBULATORIAL é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG4M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ALTA COMPLEXIDADE do Nível de Atenção AMBULATORIAL é MUNICIPAL, onde: 1-sim 0-não'},
    'NIVATE_A': {'type': 'CHAR (1)', 'description': 'Indica a existência de Nível de Atenção AMBULATORIAL, de gestão Municipal/Estadual, para este CNES, onde: 1-sim 0-não'},
    'GESPRG3E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão do programa é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG3M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão do programa é MUNICIPAL, onde: 1-sim 0-não'},
    'GESPRG5E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade MÉDIA COMPLEXIDADE do Nível de Atenção HOSPITALAR é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG5M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade MÉDIA COMPLEXIDADE do Nível de Atenção HOSPITALAR é MUNICIPAL, onde: 1-sim 0-não'},
    'GESPRG6E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ALTA COMPLEXIDADE do Nível de Atenção HOSPITALAR é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG6M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ALTA COMPLEXIDADE do Nível de Atenção HOSPITALAR é MUNICIPAL, onde: 1-sim 0-não'},
    'NIVATE_H': {'type': 'CHAR (1)', 'description': 'Indica a existência de Nível de Atenção HOSPITALAR, de gestão Municipal/Estadual, para este CNES, onde: 1-sim 0-não'},
    'AP01CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio SUS, onde: 1-sim 0-não'},
    'AP01CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP01CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP01CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP01CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PLANO-SEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP01CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PLANO-SEGURO TERCEIRO, onde: 1-sim 0-não'},
    'AP02CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio SUS, onde: 1-sim 0-não'},
    'AP02CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP02CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP02CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP02CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PLANOSEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP02CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PLANOSEGURO TERCEIRO, onde: 1-sim 0-não'},
    'AP03CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/Convenio SUS, onde: 1-sim 0-não'},
    'AP03CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP03CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP03CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP03CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/Convenio PLANO-SEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP03CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/Convenio PLANO-SEGURO TERCEIRO, onde: 1-sim 0-não'},
    'AP04CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio SUS, onde: 1-sim 0-não'},
    'AP04CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP04CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP04CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP04CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio PLANO-SEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP04CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio PLANO-SEGURO TERCEIRO, onde: 1-sim 0-não'},
    'AP05CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio SUS,onde: 1-sim 0-não'},
    'AP05CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP05CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP05CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP05CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PLANO-SEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP05CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PLANO-SEGURO TERCEIRO, onde: 1-sim 0-não'},
    'AP06CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio SUS, onde: 1-sim 0-não'},
    'AP06CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP06CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP06CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP06CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/ Convenio PLANO-SEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP06CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/ Convenio PLANO-SEGURO TERCEIRO, onde: 1-sim 0-não'},
    'AP07CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio SUS, onde: 1-sim 0-não'},
    'AP07CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP07CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP07CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP07CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PLANO-SEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP07CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PLANO-SEGURO TERCEIRO, onde: 1-sim 0-não'},
    'ATEND_PR': {'type': 'CHAR (1)', 'description': 'Indica a existência de algum atendimento prestado para este CNES, onde: 1-sim / 0-não'},
    'ID_EQUIPE': {'type': 'CHAR (18)', 'description': 'Código do Município + Código da Área da Equipe + Seqüencial da Equipe'},
    'TIPO_EQP': {'type': 'CHAR (2)', 'description': 'Tipo de Equipe'},
    'NOME_EQP': {'type': 'CHAR (60)', 'description': 'Nome da Equipe'},
    'AREA_EQP': {'type': 'CHAR (10)', 'description': 'Código da Área da Equipe'},
    'NOMEAREA': {'type': 'CHAR (60)', 'description': 'Nome da Área'},
    'ID_SEGM': {'type': 'CHAR (8)', 'description': 'Código do Segmento'},
    'DESCSEGM': {'type': 'CHAR (60)', 'description': 'Descrição do Segmento'},
    'TIPOSEGM': {'type': 'CHAR (1)', 'description': 'Tipo do Segmento: 1–Urbano 2–Rural'},
    'DT_ATIVA': {'type': 'CHAR (6)', 'description': 'Ano e Mês da Data de ATIVAÇÃO da Equipe'},
    'DT_DESAT': {'type': 'CHAR (6)', 'description': 'Ano e Mês da Data de DESATIVAÇÃO da Equipe'},
    'QUILOMBO': {'type': 'CHAR (1)', 'description': 'Atende População Assistida Quilombolas: 1-Sim 0-Não'},
    'ASSENTAD': {'type': 'CHAR (1)', 'description': 'Atende População Assistida Assentados: 1– Sim 0-Não'},
    'POPGERAL': {'type': 'CHAR (1)', 'description': 'Atende População Assistida Geral: 1-Sim 0-Não'},
    'ESCOLA': {'type': 'CHAR (1)', 'description': 'Atende População Assistida Escolares: 1-Sim 0-Não'},
    'INDIGENA': {'type': 'CHAR (1)', 'description': 'Atende População Assistida PRONASCI: 1-Sim 0-Não'},
    'PRONASCI': {'type': 'CHAR (1)', 'description': 'Atende População Assistida Geral: 1-Sim 0-Não'},
    'MOTDESAT': {'type': 'CHAR (2)', 'description': 'Código do Motivo de Desativação da Equipe'},
    'TP_DESAT': {'type': 'CHAR (1)', 'description': 'Código do Tipo de Desativação da Equipe 1 – Temporário 2 - Definitivo'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'},
    'NAT_JUR': {'type': 'CHAR (4)', 'description': 'Natureza Jurídica'}
}


eq_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (6)', 'description': 'Código do município do estabelecimento UF+MUNIC (sem dígito)'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde'},
    'DISTRSAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Código do distrito administrativo'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física3-Jurídica'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF, caso pessoa física OU CNPJ, caso pessoa jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência, onde: 1-Individual 3-Mantida'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do Estabelecimento'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de fluxo da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TERCEIRO': {'type': 'CHAR (1)', 'description': 'O estabelecimento é terceiro: 1-Sim 0-Não'},
    'TIPEQUIP': {'type': 'CHAR (1)', 'description': 'Código do tipo do equipamento'},
    'CODEQUIP': {'type': 'CHAR (2)', 'description': 'Código do equipamento'},
    'QT_EXIST': {'type': 'CHAR(3)', 'description': 'Quantidade existente do equipamento'},
    'QT_USO': {'type': 'CHAR(3)', 'description': 'Quantidade em uso do equipamento'},
    'IND_SUS': {'type': 'CHAR(1)', 'description': 'Indicador de disponibilidade para o SUS, onde: 1 =SIM 0 = NÃO'},
    'IND_NSUS': {'type': 'CHAR(1)', 'description': 'Indicador de EQUIPAMENTO NÃO DISPONÍVEL para o SUS, onde: 1 = SIM 0 = NÃO'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'},
    'NAT_JUR': {'type': 'CHAR (4)', 'description': 'Natureza Jurídica'}
}


gm_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (6)', 'description': 'Código do município do estabelecimento UF+MUNIC (sem dígito)'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde'},
    'DISTRSAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Código do distrito administrativo'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física 3-Jurídica'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF do Estabelecimento, caso pessoa física OU CNPJ, caso pessoa jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência: 1-Individual 3-Mantida'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do Estabelecimento'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de fluxo da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade (Estabelecimento)'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TERCEIRO': {'type': 'CHAR (1)', 'description': 'O estabelecimento é terceiro: 1-Sim 0-Não 2-não'},
    'COD_CEP': {'type': 'CHAR (8)', 'description': 'CEP do estabelecimento'},
    'VINC_SUS': {'type': 'CHAR (2)', 'description': 'Vínculo com SUS: 1-Sim 0-Não'},
    'TP_PREST': {'type': 'CHAR(2)', 'description': 'Tipo de Prestador'},
    'SGRUPHAB': {'type': 'CHAR(4)', 'description': 'Código da habilitação'},
    'CMPT_INI': {'type': 'CHAR(6)', 'description': 'Competência inicial'},
    'CMPT_FIM': {'type': 'CHAR(6)', 'description': 'Competência final'},
    'DTPORTAR': {'type': 'CHAR (10)', 'description': 'Data da portaria'},
    'PORTARIA': {'type': 'CHAR (50)', 'description': 'Portaria'},
    'MAPORTAR': {'type': 'CHAR (6)', 'description': 'Campo DT_PORTARIA formatado como AAAAMM'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'},
    'NAT_JUR': {'type': 'CHAR (6)', 'description': 'Natureza Jurídica'}
}


hb_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (6)', 'description': 'Código do município do estabelecimento UF+ MUNIC (sem dígito)'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde'},
    'DISTRSAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Código do distrito administrativo'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física 3-Jurídica'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF do Estabelecimento, caso pessoa física OU CNPJ, caso pessoa jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência: 1-Individual 3-Mantida'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do Estabelecimento'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de fluxo da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade (Estabelecimento)'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TERCEIRO': {'type': 'CHAR (1)', 'description': 'O estabelecimento é terceiro: 1-Sim 0-Não 2-não'},
    'COD_CEP': {'type': 'CHAR (8)', 'description': 'CEP do estabelecimento'},
    'VINC_SUS': {'type': 'CHAR (2)', 'description': 'Vínculo com SUS: 1-Sim 0-Não'},
    'TP_PREST': {'type': 'CHAR(2)', 'description': 'Tipo de Prestador'},
    'SGRUPHAB': {'type': 'CHAR(4)', 'description': 'Código da habilitação'},
    'CMPT_INI': {'type': 'CHAR(6)', 'description': 'Competência inicial'},
    'CMPT_FIM': {'type': 'CHAR(6)', 'description': 'Competência final'},
    'DTPORTAR': {'type': 'CHAR (10)', 'description': 'Data da portaria'},
    'PORTARIA': {'type': 'CHAR (50)', 'description': 'Portaria'},
    'MAPORTAR': {'type': 'CHAR (6)', 'description': 'Campo DT_PORTARIA formatado como AAAAMM'},
    'NULEITOS': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'},
    'NAT_JUR': {'type': 'CHAR (6)', 'description': 'Natureza Jurídica'}
}


in_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (6)', 'description': 'Código do município do estabelecimento UF+ MUNIC (sem dígito)'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde'},
    'DISTRSAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Código do distrito administrativo'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física 3-Jurídica'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF do Estabelecimento, caso pessoa física OU CNPJ, caso pessoa jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência: 1-Individual 3-Mantida'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do Estabelecimento'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de fluxo da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade (Estabelecimento)'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TERCEIRO': {'type': 'CHAR (1)', 'description': 'O estabelecimento é terceiro: 1-Sim 0-Não 2-não'},
    'COD_CEP': {'type': 'CHAR (8)', 'description': 'CEP do estabelecimento'},
    'VINC_SUS': {'type': 'CHAR (2)', 'description': 'Vínculo com SUS: 1-Sim 0-Não'},
    'TP_PREST': {'type': 'CHAR(2)', 'description': 'Tipo de Prestador'},
    'SGRUPHAB': {'type': 'CHAR(4)', 'description': 'Código da habilitação'},
    'CMPT_INI': {'type': 'CHAR(6)', 'description': 'Competência inicial'},
    'CMPT_FIM': {'type': 'CHAR(6)', 'description': 'Competência final'},
    'DTPORTAR': {'type': 'CHAR (10)', 'description': 'Data da portaria'},
    'PORTARIA': {'type': 'CHAR (50)', 'description': 'Portaria'},
    'MAPORTAR': {'type': 'CHAR (6)', 'description': 'Campo DT_PORTARIA formatado como AAAAMM'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'}
}


rc_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (6)', 'description': 'Código do município do estabelecimento UF+ MUNIC (sem dígito)'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde'},
    'DISTRSAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Código do distrito administrativo'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física 3-Jurídica'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF do Estabelecimento, caso pessoa física OU CNPJ, caso pessoa jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência: 1-Individual 3-Mantida'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do Estabelecimento'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de fluxo da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade (Estabelecimento)'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TERCEIRO': {'type': 'CHAR (1)', 'description': 'O estabelecimento é terceiro: 1-Sim 0-Não 2-não'},
    'COD_CEP': {'type': 'CHAR (8)', 'description': 'CEP do estabelecimento'},
    'VINC_SUS': {'type': 'CHAR (2)', 'description': 'Vínculo com SUS: 1-Sim 0-Não'},
    'TP_PREST': {'type': 'CHAR(2)', 'description': 'Tipo de Prestador'},
    'SGRUPHAB': {'type': 'CHAR(4)', 'description': 'Código da habilitação'},
    'CMPT_INI': {'type': 'CHAR(6)', 'description': 'Competência inicial'},
    'CMPT_FIM': {'type': 'CHAR(6)', 'description': 'Competência final'},
    'DTPORTAR': {'type': 'CHAR (10)', 'description': 'Data da portaria'},
    'PORTARIA': {'type': 'CHAR (50)', 'description': 'Portaria'},
    'MAPORTAR': {'type': 'CHAR (6)', 'description': 'Campo DT_PORTARIA formatado como AAAAMM'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'},
    'NAT_JUR': {'type': 'CHAR (4)', 'description': 'Natureza Jurídica'}
}


sr_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (6)', 'description': 'Código do município do estabelecimento UF+ MUNIC (sem dígito)'},
    'SERV_ESP': {'type': 'CHAR (3)', 'description': 'Código do serviço especializado'},
    'CLASS_SR': {'type': 'CHAR (3)', 'description': 'Código da classificação do serviço ou ‘999’, caso INEXISTENTE'},
    'SRVUNICO': {'type': 'CHAR (3)', 'description': 'Código do serviço especializado ÚNICO (O PREENCHIMENTO deste campo acontece somente uma vez por chave única CNES + SERV_ESP)'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde'},
    'DISTRSAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Código do distrito administrativo'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física 3-Jurídica'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF do Estabelecimento, caso pessoa física ou CNPJ, caso pessoa jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência, onde: 1-Individual 3-Mantida'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de fluxo da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade (Estabelecimento)'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TERCEIRO': {'type': 'CHAR (1)', 'description': 'O estabelecimento é terceiro: 1-Sim 0-Não'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do estabelecimento'},
    'CARACTER': {'type': 'CHAR (1)', 'description': 'Caracterização do serviço'},
    'AMB_HOSP': {'type': 'CHAR (4)', 'description': 'Indica se o Serviço é Ambulatorial Não SUS / Ambulatorial SUS / Hospitalar Não SUS / Hospitalar SUS, onde: 1 – Sim 0 – Não'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'},
    'CONTSRVU': {'type': 'CHAR (1)', 'description': 'INDICADOR de serviço especializado ÚNICO'},
    'CNESTERC': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde TERCEIRO'},
    'NAT_JUR': {'type': 'CHAR (4)', 'description': 'Natureza Jurídica'}
}


st_dict = {
    'CNES': {'type': 'CHAR (7)', 'description': 'Número nacional do estabelecimento de saúde'},
    'CODUFMUN': {'type': 'CHAR (7)', 'description': 'Código do município do estabelecimento: UF + MUNIC (sem dígito)'},
    'COD_CEP': {'type': 'CHAR (8)', 'description': 'Código do CEP do estabelecimento'},
    'CPF_CNPJ': {'type': 'CHAR (14)', 'description': 'CPF do estabelecimento, caso pessoa física ou CNPJ, caso pessoa jurídica'},
    'PF_PJ': {'type': 'CHAR (1)', 'description': 'Indicador de pessoa: 1-Física 3-Jurídica'},
    'NIV_DEP': {'type': 'CHAR (1)', 'description': 'Grau de dependência, onde: 1-Individual 3-Mantida'},
    'CNPJ_MAN': {'type': 'CHAR (14)', 'description': 'CNPJ da mantenedora do estabelecimento.'},
    'COD_IR': {'type': 'CHAR (2)', 'description': 'Indica o tipo de retenção de tributos da mantenedora'},
    'REGSAUDE': {'type': 'CHAR (4)', 'description': 'Código da região de saúde NOAS'},
    'MICR_REG': {'type': 'CHAR (6)', 'description': 'Código da micro-região de saúde NOAS'},
    'DISTRSAN': {'type': 'CHAR (4)', 'description': 'Código do distrito sanitário'},
    'DISTRADM': {'type': 'CHAR (4)', 'description': 'Inicialmente chamado Distrito Administrativo, atualmente Código do Módulo Assistencial conforme tabela local, em conformidade com o Plano Diretor de Regionalização do Estado/Município.'},
    'VINC_SUS': {'type': 'CHAR (1)', 'description': 'Vínculo com SUS: 1-Sim 0-Não'},
    'TPGESTAO': {'type': 'CHAR (1)', 'description': 'Gestão de saúde'},
    'ESFERA_A': {'type': 'CHAR (2)', 'description': 'Código da esfera administrativa'},
    'ATIVIDAD': {'type': 'CHAR (2)', 'description': 'Código da atividade de ensino/pesquisa'},
    'RETENCAO': {'type': 'CHAR (2)', 'description': 'Código de retenção de tributos'},
    'NATUREZA': {'type': 'CHAR (2)', 'description': 'Código da natureza da organização'},
    'CLIENTEL': {'type': 'CHAR (2)', 'description': 'Código de FLUXO da clientela'},
    'TP_UNID': {'type': 'CHAR (2)', 'description': 'Tipo de unidade (estabelecimento)'},
    'TURNO_AT': {'type': 'CHAR (2)', 'description': 'Código de turno de atendimento'},
    'NIV_HIER': {'type': 'CHAR (2)', 'description': 'Código do nível de hierarquia'},
    'TP_PREST': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'CO_BANCO': {'type': 'CHAR (4)', 'description': 'Código do Banco do Estabelecimento'},
    'CO_AGENC': {'type': 'CHAR (5)', 'description': 'Código da Agência do Estabelecimento'},
    'C_CORREN': {'type': 'CHAR (14)', 'description': 'Código da Conta Corrente do Estabelecimento'},
    'CONTRATM': {'type': 'CHAR (11)', 'description': 'Número do contrato/convênio MUNICIPAL do vínculo com o SUS'},
    'DT_PUBLM': {'type': 'CHAR (8)', 'description': 'Ano e Mês de publicação do contrato /convênio MUNICIPAL (AAAAMM)'},
    'CONTRATE': {'type': 'CHAR (20)', 'description': 'Número do contrato/convênio ESTADUAL do vínculo com o SUS'},
    'DT_PUBLE': {'type': 'CHAR (8)', 'description': 'Ano e Mês de publicação do contrato /convênio ESTADUAL (AAAAMM)'},
    'ALVARA': {'type': 'CHAR (25)', 'description': 'Número do alvará'},
    'DT_EXPED': {'type': 'CHAR (8)', 'description': 'Ano e Mês de da expedição do alvará (AAAAMM)'},
    'ORGEXPED': {'type': 'CHAR (2)', 'description': 'Órgão expedidor do alvará, onde: 1-SES 2-SMS'},
    'AV_ACRED': {'type': 'CHAR (1)', 'description': 'Indica se o estabelecimento foi avaliado segundo o Manual de Acreditação Hospitalar do MS, onde: 1-Sim 2-Não'},
    'CLASAVAL': {'type': 'CHAR (1)', 'description': 'Classificação da avaliação do estabelecimento segundo o Manual de Acreditação Hospitalar do MS'},
    'DT_ACRED': {'type': 'CHAR (6)', 'description': 'Ano e Mês da Acreditação (AAAAMM)'},
    'AV_PNASS': {'type': 'CHAR (1)', 'description': 'Indica se o estabelecimento foi avaliado segundo o Programa Nacional de Serviços de Saúde - PNASS, onde: 1-Sim 2-Não'},
    'DT_PNASS': {'type': 'CHAR (6)', 'description': 'Ano e Mês da Avaliação PNASS (AAAAMM)'},
    'GESPRG1E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ATENÇÃO BÁSICA do Nível de Atenção AMBULATORIAL é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG1M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ATENÇÃO BÁSICA do Nível de Atenção AMBULATORIAL é MUNICIPAL, onde: 1-sim 0-não'},
    'GESPRG2E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade MÉDIA COMPLEXIDADE do Nível de Atenção AMBULATORIAL é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG2M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade MÉDIA COMPLEXIDADE do Nível de Atenção AMBULATORIAL é MUNICIPAL, onde: 1-sim 0-não'},
    'GESPRG4E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ALTA COMPLEXIDADE do Nível de Atenção AMBULATORIAL é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG4M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ALTA COMPLEXIDADE do Nível de Atenção AMBULATORIAL é MUNICIPAL, onde: 1-sim 0-não'},
    'NIVATE_A': {'type': 'CHAR (1)', 'description': 'Indica a existência de Nível de Atenção AMBULATORIAL, de gestão Municipal/Estadual, para este CNES, onde: 1-sim 0-não'},
    'GESPRG3E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão do programa cód. 03 é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG3M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão do programa cód. 03 é MUNICIPAL, onde: 1-sim 0-não'},
    'GESPRG5E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade MÉDIA COMPLEXIDADE do Nível de Atenção HOSPITALAR é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG5M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade MÉDIA COMPLEXIDADE do Nível de Atenção HOSPITALAR é MUNICIPAL, onde: 1-sim 0-não'},
    'GESPRG6E': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ALTA COMPLEXIDADE do Nível de Atenção HOSPITALAR é ESTADUAL, onde: 1-sim 0-não'},
    'GESPRG6M': {'type': 'CHAR (1)', 'description': 'Indicador se a gestão da atividade ALTA COMPLEXIDADE do Nível de Atenção HOSPITALAR é MUNICIPAL, onde: 1-sim 0-não'},
    'NIVATE_H': {'type': 'CHAR (1)', 'description': 'Indica a existência de Nível de Atenção HOSPITALAR, de gestão Municipal/Estadual, para este CNES, onde: 1-sim 0-não'},
    'QTLEITP1': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos tipo 1 (cirúrgico) existentes'},
    'QTLEITP2': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos tipo 2 (clínico) existentes'},
    'QTLEITP3': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos tipo 3 (complem.) existentes'},
    'LEITHOSP': {'type': 'CHAR (1)', 'description': 'Indica a existência de LEITOS HOSPITALARES-CIRPURGICOS, CLÍNICOS E COMPLEMENTARES para este CNES, onde: 1-sim 0-não'},
    'QTINST01': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST02': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST03': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST04': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST05': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST06': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST07': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST08': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST09': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST10': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST11': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST12': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST13': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST14': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'URGEMERG': {'type': 'CHAR (1)', 'description': 'Indica a existência de INSTALAÇÃO FÍSICA de URGÊNCIA/EMERGÊNCIA para este CNES, onde: 1-sim 0-não'},
    'QTINST15': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST16': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST17': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST18': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST19': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST20': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST21': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST22': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST23': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST24': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST25': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST26': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST27': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST28': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST29': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST30': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'ATENDAMB': {'type': 'CHAR (1)', 'description': 'Indica a existência de INSTALAÇÃO FÍSICA de ATENDIMENTO AMBULATORIAL para este CNES, onde: 1-sim 0-não'},
    'QTINST31': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST32': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST33': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'CENTRCIR': {'type': 'CHAR (1)', 'description': 'Indica a existência de INSTALAÇÃO FÍSICA de ATENDIMENTO HOSPITALARCENTRO CIRÚRGICO para este CNES, onde: 1-sim 0-não'},
    'QTINST34': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST35': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST36': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'QTINST37': {'type': 'NUMERIC (3)', 'description': 'Quantidade de salas/consultórios'},
    'CENTROBS': {'type': 'CHAR (1)', 'description': 'Indica a existência de INSTALAÇÃO FÍSICA de ATENDIMENTO HOSPITALARCENTRO OBSTÉTRICO para este CNES, onde: 1-sim 0-não'},
    'QTLEIT05': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT06': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT07': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT09': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT19': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT20': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT21': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT21': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT22': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT23': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT32': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT34': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT38': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT39': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'QTLEIT40': {'type': 'NUMERIC (3)', 'description': 'Quantidade de leitos/equipos'},
    'CENTRNEO': {'type': 'CHAR (1)', 'description': 'Indica a existência de INSTALAÇÃO FÍSICA de ATENDIMENTO HOSPITALARUNIDADE NEONATAL para este CNES, onde: 1-sim 0-não'},
    'ATENDHOS': {'type': 'CHAR (1)', 'description': 'Indica a existência de INSTALAÇÃO FÍSICA de ATENDIMENTO HOSPITALAR para este CNES, onde: 1-sim 0-não'},
    'SERAP01P': {'type': 'CHAR (1)', 'description': 'Serviço de apoio S.A.M.E. ou S.P.P. próprio, onde: 1-sim 0-não'},
    'SERAP01T': {'type': 'CHAR (1)', 'description': 'Serviço de apoio S.A.M.E. ou S.P.P. terceirizado, onde: 1-sim 0-não'},
    'SERAP02P': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Serviço Social próprio, onde: 1-sim 0-não'},
    'SERAP02T': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Serviço Social terceirizado, onde: 1-sim 0-não'},
    'SERAP03P': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Farmácia próprio, onde: 1-sim 0-não'},
    'SERAP03T': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Farmácia terceirizado, onde: 1-sim 0-não'},
    'SERAP04P': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Esterilização de Materiais próprio, onde: 1-sim 0-não'},
    'SERAP04T': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Esterilização de Materiais terceirizado, onde: 1-sim 0-não'},
    'SERAP05P': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Nutrição/Dietética (S.N.D.) próprio, onde: 1-sim 0-não'},
    'SERAP05T': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Nutrição/Dietética (S.N.D.) terceirizado, onde: 1-sim 0-não'},
    'SERAP06P': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Lactário próprio, onde: 1-sim 0-não'},
    'SERAP06T': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Lactário terceirizado, onde: 1-sim 0-não'},
    'SERAP07P': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Banco De Leite próprio, onde: 1-sim 0-não'},
    'SERAP07T': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Banco De Leite terceirizado, onde: 1-sim 0-não'},
    'SERAP08P': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Lavanderia próprio, onde: 1-sim 0-não'},
    'SERAP08T': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Lavanderia terceirizado, onde: 1-sim 0-não'},
    'SERAP09P': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Manutenção de Equipamento próprio, onde: 1-sim 0-não'},
    'SERAP09T': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Manutenção de Equipamento terceirizado, onde: 1-sim 0-não'},
    'SERAP10P': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Ambulância próprio, onde: 1-sim 0-não'},
    'SERAP10T': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Ambulância terceirizado, onde: 1-sim 0-não'},
    'SERAP11P': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Necrotério próprio, onde: 1-sim 0-não'},
    'SERAP11T': {'type': 'CHAR (1)', 'description': 'Serviço de apoio Necrotério terceirizado, onde: 1-sim 0-não'},
    'SERAPOIO': {'type': 'CHAR (1)', 'description': 'Indica a existência de algum serviço de apoio para este CNES, onde: 1-sim 0-não'},
    'RES_BIOL': {'type': 'CHAR (1)', 'description': 'Existe coleta de resíduo biológico, onde: 1-sim 0-não'},
    'RES_QUIM': {'type': 'CHAR (1)', 'description': 'Existe coleta de resíduo químico, onde: 1-sim 0-não'},
    'RES_RADI': {'type': 'CHAR (1)', 'description': 'Existe coleta de rejeitos radioativos, onde: 1-sim 0-não'},
    'RES_COMU': {'type': 'CHAR (1)', 'description': 'Existe coleta de resíduos comuns, onde: 1-sim 0-não'},
    'COLETRES': {'type': 'CHAR (1)', 'description': 'Indica a existência de alguma coleta de resíduo para este CNES, onde: 1-sim 0-não'},
    'COMISS01': {'type': 'CHAR (1)', 'description': 'Existe comissão de ETICA MEDICA, onde: 1-sim 0-não'},
    'COMISS02': {'type': 'CHAR (1)', 'description': 'Existe comissão de ETICA DE ENFERMAGEM, onde: 1-sim 0-não'},
    'COMISS03': {'type': 'CHAR (1)', 'description': 'Existe comissão de FARMÁCIA E TERAPÊUTICA, onde: 1-sim 0-não'},
    'COMISS04': {'type': 'CHAR (1)', 'description': 'Existe comissão de CONTROLE DE INFECÇÃO HOSPITALAR, onde: 1-sim 0-não'},
    'COMISS05': {'type': 'CHAR (1)', 'description': 'Existe comissão de APROPRIAÇÃO DE CUSTOS, onde: 1-sim 0-não'},
    'COMISS06': {'type': 'CHAR (1)', 'description': 'Existe comissão de CIPA, onde: 1-sim 0-não'},
    'COMISS07': {'type': 'CHAR (1)', 'description': 'Existe comissão de REVISÃO DE PRONTUÁRIOS, onde: 1-sim 0-não'},
    'COMISS08': {'type': 'CHAR (1)', 'description': 'Existe comissão de REVISAO DE DOCUMENTACAO MEDICA E ESTATISTICA, onde: 1-sim 0-não'},
    'COMISS09': {'type': 'CHAR (1)', 'description': 'Existe comissão de ANALISE DE OBITOS E BIOPISIAS, onde: 1-sim 0-não'},
    'COMISS10': {'type': 'CHAR (1)', 'description': 'Existe comissão de INVESTIGACAO EPIDEMIOLOGICA, onde: 1-sim 0-não'},
    'COMISS11': {'type': 'CHAR (1)', 'description': 'Existe comissão de NOTIFICACAO DE DOENCAS, onde: 1-sim 0-não'},
    'COMISS12': {'type': 'CHAR (1)', 'description': 'Existe comissão de CONTROLE DE ZOONOSES E VETORES, onde: 1-sim 0-não'},
    'COMISSAO': {'type': 'CHAR (1)', 'description': 'Indica a existência de alguma comissão para este CNES, onde: 1-sim 0-não'},
    'AP01CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio SUS, onde: 1-sim 0-não'},
    'AP01CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP01CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/ Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP01CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP01CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PLANO-SEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP01CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado INTERNAÇÃO/Convenio PLANO-SEGURO TERCEIRO, onde: 1-sim 0-não'},
    'AP02CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio SUS, onde: 1-sim 0-não'},
    'AP02CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP02CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP02CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP02CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PLANOSEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP02CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado ATENDIMENTO AMBULATORIAL/Convenio PLANOSEGURO TERCEIRO, onde: 1-sim 0-não'},
    'AP03CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/ Convenio SUS, onde: 1-sim 0-não'},
    'AP03CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/ Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP03CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/ Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP03CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/ Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP03CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/ Convenio PLANO-SEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP03CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado SADT/ Convenio PLANO-SEGURO TERCEIRO, onde: 1-sim 0-não'},
    'AP04CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/ Convenio SUS, onde: 1-sim 0-não'},
    'AP04CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/ Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP04CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/ Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP04CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP04CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/ Convenio PLANO-SEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP04CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado URGENCIA/ Convenio PLANO-SEGURO TERCEIRO, onde: 1-sim 0-não'},
    'AP05CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/ Convenio SUS, onde: 1-sim 0-não'},
    'AP05CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP05CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP05CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP05CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PLANO-SEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP05CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado OUTROS/Convenio PLANO-SEGURO TERCEIRO, onde: 1-sim 0-não'},
    'AP06CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio SUS, onde: 1-sim 0-não'},
    'AP06CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP06CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP06CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP06CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PLANO-SEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP06CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado VIGILANCIA EM SAUDE/Convenio PLANO-SEGURO TERCEIRO, onde: 1-sim 0-não'},
    'AP07CV01': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio SUS, onde: 1-sim 0-não'},
    'AP07CV02': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PARTICULAR, onde: 1-sim 0-não'},
    'AP07CV05': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PLANO de SAUDE PUBLICO, onde: 1-sim 0-não'},
    'AP07CV06': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PLANO de SAUDE PRIVADO, onde: 1-sim 0-não'},
    'AP07CV03': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PLANO-SEGURO PROPRIO, onde: 1-sim 0-não'},
    'AP07CV04': {'type': 'CHAR (1)', 'description': 'Atendimento prestado REGULACAO/Convenio PLANO-SEGURO TERCEIRO, onde: 1-sim 0-não'},
    'ATEND_PR': {'type': 'CHAR (1)', 'description': 'Indica a existência de algum atendimento prestado para este CNES, onde: 1-sim / 0-não'},
    'MOTDESAB': {'type': 'CHAR(2)', 'description': 'Código do Motivo de Desabilitação do Estabelecimento'},
    'DT_ATUA': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da atualização da informação pelo estabelecimento (AAAAMM)'},
    'COMPETEN': {'type': 'CHAR (6)', 'description': 'Ano e Mês de competência da informação (AAAAMM)'},
    'NAT_JUR': {'type': 'CHAR (4)', 'description': 'Natureza Jurídica'}
}