pce_dict = {
    'ID_UF': {'type': 'CHAR (2)', 'description': 'Unidade da Federação (UF) onde foi executada a atividade do programa.'},
    'SG_UF': {'type': 'CHAR (2)', 'description': 'Unidade da Federação (UF) onde foi executada a atividade do programa.'},
    'ID_DISTR': {'type': 'CHAR (2)', 'description': 'Código do Distrito e Regional de Saúde onde foi executada a atividade do programa.'},
    'ID_LOC': {'type': 'CHAR (12)', 'description': 'Localidade (bairro, vila, povoado, fazenda, sítio etc) onde foi executada a atividade do programa.'},
    'DT_COMP': {'type': 'CHAR (6)', 'description': 'Mês e o ano em que a atividade do programa foi executada.'},
    'QT_POP': {'type': 'NUMERIC', 'description': 'População trabalhada: número de pessoas que receberam o recipiente para coleta do material para exame.'},
    'QT_PRED': {'type': 'NUMERIC', 'description': 'Número de domicílios/prédios visitados.'},
    'QT_EXAM': {'type': 'NUMERIC', 'description': 'Número de pessoas examinadas (coproscopia).'},
    'QT_NRECOL': {'type': 'NUMERIC', 'description': 'Número de recipientes não recolhidos.'},
    'QT_1A4': {'type': 'NUMERIC', 'description': 'Número de pessoas cujo exame da lâmina identificou entre 1 a 4 ovos.'},
    'QT_5A16': {'type': 'NUMERIC', 'description': 'Número de pessoas cujo exame da lâmina identificou entre 5 a 16 ovos.'},
    'QT_17': {'type': 'NUMERIC', 'description': 'Número de pessoas cujo exame da lâmina identificou 17 ovos ou mais.'},
    'QT_POS': {'type': 'NUMERIC', 'description': 'Número de pessoas cujos exames foram identificados com ovos de Schistosoma mansoni.'},
    'QT_ATRAT': {'type': 'NUMERIC', 'description': 'Número de pessoas previstas para serem medicadas contra a esquistossomose. Não significa que todos são positivos.'},
    'QT_TRAT': {'type': 'NUMERIC', 'description': 'Número de pessoas tratadas contra a esquistossomose.'},
    'QT_CI': {'type': 'NUMERIC', 'description': 'Número de pessoas não tratadas por contraindicação: - Doenças cardíacas; - Estado febril; - Epilepsia ou outras doenças neurológicas; - Gravidez; - Amamentação; - Outros motivos.'},
    'QT_REC': {'type': 'NUMERIC', 'description': 'Número de pessoas não tratadas por recusa.'},
    'QT_AUS': {'type': 'NUMERIC', 'description': 'Número de pessoas não tratadas por ausência.'},
    'QT_ASC': {'type': 'NUMERIC', 'description': 'Número de pessoas cujo exame da lâmina identificou ovos de Ascaris lumbricoides.'},
    'QT_ANC': {'type': 'NUMERIC', 'description': 'Número de pessoas cujo exame da lâmina identificou ovos de Ancilostomo duodenale.'},
    'QT_TAE': {'type': 'NUMERIC', 'description': 'Número de pessoas cujo exame da lâmina identificou ovos de Taenia.'},
    'QT_TT': {'type': 'NUMERIC', 'description': 'Número de pessoas cujo exame da lâmina identificou ovos de Trichocephalus trichiura.'},
    'QT_EV': {'type': 'NUMERIC', 'description': 'Número de pessoas cujo exame da lâmina identificou ovos de Enterobius vermicularis.'},
    'QT_SE': {'type': 'NUMERIC', 'description': 'Número de pessoas cujo exame da lâmina identificou ovos de Strongyloides stercoralis.'},
    'QT_HN': {'type': 'NUMERIC', 'description': 'Número de pessoas cujo exame da lâmina identificou ovos de Hymenolepis nana.'},
    'QT_OUT': {'type': 'NUMERIC', 'description': 'Número de pessoas cujo exame da lâmina identificou ovos de outras verminoses.'},
    'QT_CAP': {'type': 'NUMERIC', 'description': 'Número de caramujos capturados na atividade de malacologia.'},
    'QT_PESQ': {'type': 'NUMERIC', 'description': 'Número de estações pesquisadas.'},
    'QT_BGLA': {'type': 'NUMERIC', 'description': 'Quantidade de caramujos capturados da espécie Biomphalaria glabrata.'},
    'QT_BSTR': {'type': 'NUMERIC', 'description': 'Quantidade de caramujos capturados da espécie Biomphalaria straminea.'},
    'QT_BTEN': {'type': 'NUMERIC', 'description': 'Quantidade de caramujos capturados da espécie Biomphalaria tenagophila.'},
    'QT_OUT1': {'type': 'NUMERIC', 'description': 'Quantidade de caramujos capturados de outras espécies.'},
    'QT_POSBGLA': {'type': 'NUMERIC', 'description': 'Quantidade de caramujos positivos da espécie Biomphalaria glabrata.'},
    'QT_POSBTEN': {'type': 'NUMERIC', 'description': 'Quantidade de caramujos positivos da espécie Biomphalaria tenagophila.'},
    'QT_POSBSTR': {'type': 'NUMERIC', 'description': 'Quantidade de caramujos positivos da espécie Biomphalaria straminea.'},
    'QT_POSOUT': {'type': 'NUMERIC', 'description': 'Quantidade de caramujos positivos de outras espécies.'}
}