po_dict = {
    'ANO_DIAGN': {'type': 'CHAR (4)', 'description': 'Ano de diagnóstico no formato AAAA'},
    'ANOMES_DIA': {'type': 'CHAR (6)', 'description': 'Ano e mês do diagnóstico no formato AAAAMM'},
    'ANO_TRATAM': {'type': 'CHAR (4)', 'description': 'Ano do primeiro tratamento registrado no formato AAAA'},
    'ANOMES_TRA': {'type': 'CHAR (6)', 'description': 'Ano e mês do primeiro tratamento registrado no formato AAAAMM'},
    'UF_RESID': {'type': 'CHAR (2)', 'description': 'Cód. da Unidade de Federação de residência, conforme código IBGE'},
    'MUN_RESID': {'type': 'CHAR (6)', 'description': 'Cód. da Unidade de Federação de residência + Cód. do Município de residência, conforme código IBGE'},
    'UF_TRATAM': {'type': 'CHAR (2)', 'description': 'Cód. da Unidade de Federação do estabelecimento onde foi registrado o primeiro tratamento, conforme código IBGE'},
    'MUN_TRATAM': {'type': 'CHAR (6)', 'description': 'Cód. da Unidade de Federação de residência + Cód. do Município de residência do estabelecimento onde foi registrado o primeiro tratamento, conforme código IBGE'},
    'UF_DIAGN': {'type': 'CHAR (2)', 'description': 'Cód. da Unidade de Federação do estabelecimento onde foi registrado o diagnóstico, conforme código IBGE'},
    'MUN_DIAG': {'type': 'CHAR (6)', 'description': 'Cód. da Unidade de Federação de residência + Cód. do Município de residência do estabelecimento onde foi registrado o diagnóstico, conforme código IBGE'},
    'TRATAMENTO': {'type': 'CHAR (1)', 'description': 'Primeiro tratamento registrado: 1 - Cirurgia, 2 - Quimioterapia, 3 - Radioterapia, 4 - Quimioterapia + Radioterapia, 5 - Sem informação de tratamento'},
    'DIAGNOSTIC': {'type': 'CHAR (2)', 'description': 'Categorias de diagnóstico: 1 - Neoplasias Malignas (Lei no 12.732/12), 2 - Neoplasias in situ, 3 - Neoplasias de comportamento incerto ou desconhecido, 4 - C44 e C73'},
    'IDADE': {'type': 'CHAR (3)', 'description': 'Idade do(a) paciente no momento do diagnóstico, de 000 a 999, sendo 999 = idade ignorada'},
    'SEXO': {'type': 'CHAR (1)', 'description': 'Sexo do paciente F - Feminino M - Masculino'},
    'ESTADIAM': {'type': 'CHAR (1)', 'description': 'Estadiamento registrado da doença* 0 - 0, 1 - I, 2 - II, 3 - III, 4 - IV, 5 - Não se aplica, 9 - Ignorado'},
    'CNES_DIAG': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento no CNES (Cadastro Nacional de Estabelecimentos de Saúde) onde foi registrado o diagnóstico'},
    'CNES_TRAT': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento no CNES (Cadastro Nacional de Estabelecimentos de Saúde) onde foi registrado o primeiro tratamento'},
    'TEMPO_TRAT': {'type': 'CHAR (5)', 'description': 'Intervalo de tempo entre o diagnóstico e o primeiro tratamento registrados. 99999 – Sem informação de tratamento Para os casos com informação de tratamento, o campo é composto de dois subcampos. O primeiro, de 1 dígito indica se o tratamento ocorreu antes ou depois do laudo de diagnóstico: ( + ) - tratamento com data registrada posterior ao laudo diagnóstico ( - ) – tratamento com data registrada anterior ao laudo diagnóstico O segundo, composto de quatro dígitos, indica o número de dias.'},
    'CNS_PAC': {'type': 'CHAR (15)', 'description': 'Cartão Nacional de Saúde'},
    'DIAG_DETH': {'type': 'CHAR (3)', 'description': 'Diagnóstico detalhado registrado Lista de CID - 10ª Revisão C00 ao C97 D00 ao D09 D37 ao D48'},
    'DT_DIAG': {'type': 'CHAR (10)', 'description': 'Data detalhada do diagnóstico registrado no formato DD/MM/AAAA'},
    'DT_TRAT': {'type': 'CHAR (10)', 'description': 'Data detalhada do primeiro tratamento registrado no formato DD/MM/AAAA'},
    'DT_NASC': {'type': 'CHAR (10)', 'description': 'Data de nascimento do paciente no formato DD/MM/AAAA'}
}