resp_dict = {
    'CO_SEQ': {'type': 'CHAR (12)', 'description': 'Código sequencial de identificação do registro na base de dados de disseminação.'},
    'DT_NOTIFIC': {'type': 'CHAR (8)', 'description': 'Data de preenchimento do formulário'},
    'ANO_NOT': {'type': 'CHAR (4)', 'description': 'Ano da notificação'},
    'TP_NOTIFIC': {'type': 'CHAR (1)', 'description': 'Tipo da notificação'},
    'IDADEGES': {'type': 'CHAR (2)', 'description': 'Idade da gestante/mãe'},
    'RACACOR': {'type': 'CHAR (1)', 'description': 'Cor ou raça declarada'},
    'REGIAORES': {'type': 'CHAR (1)', 'description': 'Macrorregião de residência da gestante/mãe'},
    'UFRES': {'type': 'CHAR (2)', 'description': 'Unidade da federação de residência da gestante/mãe'},
    'CODMUNRES': {'type': 'CHAR (6)', 'description': 'Municípi de residência da gestante/mãe'},
    'SEXO': {'type': 'CHAR (1)', 'description': 'Sexo da criança, recém-nascido, feto ou natimorto.'},
    'DT_NASC': {'type': 'CHAR (8)', 'description': 'Data de nascimento da criança, recém-nascido ou do feto'},
    'ANO_NASC': {'type': 'CHAR (4)', 'description': 'Ano de nascimento da criança, recém-nascido ou do feto'},
    'PESO': {'type': 'CHAR (4)', 'description': 'Peso ao nascer (ou do natimorto) em gramas'},
    'COMPRIMENT': {'type': 'CHAR (2)', 'description': 'Comprimento ao nascer (ou do natimorto) em centímetros'},
    'MICROCEFAL': {'type': 'CHAR (1)', 'description': 'Tipos de alterações congênitas detectadas'},
    'DEF_NEURO': {'type': 'CHAR (1)', 'description': 'Foi informada deficiência neurológica entre as alterações congênitas detectadas?'},
    'DEF_AUDIT': {'type': 'CHAR (1)', 'description': 'Foi informada deficiência auditiva entre as alterações congênitas detectadas?'},
    'DEF_VISUAL': {'type': 'CHAR (1)', 'description': 'Foi informada deficiência visual entre as alterações congênitas detectadas?'},
    'TPDETECCAO': {'type': 'CHAR (1)', 'description': 'Momento em que foi identificada a alteração congênita'},
    'GEST_DIAG': {'type': 'CHAR (2)', 'description': 'Idade gestacional, em semanas, em que foi detectada a alteração congênita (pode ser ainda na gestação ou momento do parto)'},
    'GRAVIDEZ': {'type': 'CHAR (1)', 'description': 'Tipo de Gravidez'},
    'CLASS_FETO': {'type': 'CHAR (1)', 'description': 'Classificação do nascido vivo ou natimorto quanto ao período gestacional no momento do parto.'},
    'PERIMCEFAL': {'type': 'CHAR (4)', 'description': 'Perímetro cefálico ao nascer (ou do natimorto) em centímetros com uma casa decimal – Exemplo: 31.5'},
    'DIAMCEFAL': {'type': 'CHAR (4)', 'description': 'Medida da Circunferência Craniana, em centímetros incluindo a decimal (exemplo: 28.5), para detecção intrauterina da alteração congênita.'},
    'DT_SINTOMA': {'type': 'CHAR (8)', 'description': 'Data provável de início de qualquer sintoma da gestante/mãe'},
    'FEBRE_GES': {'type': 'CHAR (1)', 'description': 'Febre na gestação'},
    'EXANT_GES': {'type': 'CHAR (1)', 'description': 'Exantema na gestação'},
    'PRURIDO': {'type': 'CHARv(1)', 'description': 'Foi informado prurido entre outros sinais e sintomas durante a gestação?'},
    'CONJUNTIV': {'type': 'CHAR (1)', 'description': 'Foi informada hiperemia conjuntival (Conjuntivite não purulenta) entre outros sinais e sintomas durante a gestação?'},
    'DOR_ARTIC': {'type': 'CHAR (1)', 'description': 'Foi informada dor em articulação entre outros sinais e sintomas durante a gestação?'},
    'DOR_MUSC': {'type': 'CHAR (1)', 'description': 'Foi informada dor muscular entre outros sinais e sintomas durante a gestação?'},
    'EDEMA': {'type': 'CHAR (1)', 'description': 'Foi informado edema em articulações entre outros sinais e sintomas durante a gestação?'},
    'CEFALEIA': {'type': 'CHAR (1)', 'description': 'Foi informada cefaleia entre outros sinais e sintomas durante a gestação?'},
    'HIPERT_GAN': {'type': 'CHAR (1)', 'description': 'Foi informada hipertrofia ganglionar entre outros sinais e sintomas durante a gestação?'},
    'NEUROLOG': {'type': 'CHAR (1)', 'description': 'Foi informado acometimento neurológico entre outros sinais e sintomas durante a gestação?'},
    'EXA_TORSCH': {'type': 'CHAR (1)', 'description': 'Diagnóstico laboratorial para, pelo menos, um dos STORCH (Sífilis, Toxoplasmose, Rubéola, Citomegalovírus, Herpes vírus) na gestação ou pós-parto imediato'},
    'RESUL_S': {'type': 'CHAR (1)', 'description': 'Diagnóstico laboratorial para Sífilis durante a gestação ou no pósparto imediato.'},
    'RESUL_TO': {'type': 'CHAR (1)', 'description': 'Diagnóstico laboratorial para Toxoplasmose durante a gestação ou no pós-parto imediato.'},
    'RESUL_C': {'type': 'CHAR (1)', 'description': 'Diagnóstico laboratorial para Citomegalovírus durante a gestação ou no pós-parto imediato.'},
    'RESUL_H': {'type': 'CHAR (1)', 'description': 'Diagnóstico laboratorial para Herpes vírus durante a gestação ou no pósparto imediato.'},
    'RESUL_Z': {'type': 'CHAR (1)', 'description': 'Diagnóstico laboratorial para Vírus Zika durante a gestação ou no pós-parto imediato.'},
    'SO_IGG_Z': {'type': 'CHAR (1)', 'description': 'Resultado para Sorologia IgG para Zika Vírus durante a gestação ou no pósparto imediato.'},
    'SO_IGM_Z': {'type': 'CHAR (1)', 'description': 'Resultado para Sorologia IgM para Zika Vírus durante a gestação ou no pósparto imediato.'},
    'TR_IGG_Z': {'type': 'CHAR (1)', 'description': 'Resultado do teste rápido Sorologia IgG para Zika vírus durante a gestação ou no pós-parto imediato.'},
    'TR_IGM_Z': {'type': 'CHAR (1)', 'description': 'Resultado do teste rápido Sorologia IgM para Zika vírus durante a gestação ou no pós-parto imediato.'},
    'PCR_Z': {'type': 'CHAR (1)', 'description': 'Resultado de PCR para Zika vírus durante a gestação ou no pós-parto imediato.'},
    'HIST_ARBOV': {'type': 'CHAR (1)', 'description': 'Histórico de infecção recente por outros arbovírus'},
    'HIST_MALFO': {'type': 'CHAR (1)', 'description': 'Histórico de malformação congênita em familiares/parentes'},
    'RNEXA_TORS': {'type': 'CHAR (1)', 'description': 'Diagnóstico laboratorial do recém-nascido para, pelo menos, um dos STORCH (Sífilis, Toxoplasmose, Rubéola, Citomegalovírus, Herpes vírus) na gestação ou pós-parto imediato.'},
    'RNRESUL_S': {'type': 'CHAR (1)', 'description': 'Diagnóstico laboratorial do recém-nascido para Sífilis durante a gestação ou no pós-parto imediato.'},
    'RNRESUL_TO': {'type': 'CHAR (1)', 'description': 'Diagnóstico laboratorial do recém-nascido para Toxoplasmose durante a gestação ou no pós-parto imediato.'},
    'RNRESUL_C': {'type': 'CHAR (1)', 'description': 'Diagnóstico laboratorial do recém-nascido para Citomegalovírus durante a gestação ou no pós-parto imediato.'},
    'RNRESUL_H': {'type': 'CHAR (1)', 'description': 'Diagnóstico laboratorial do recém-nascido para Herpes vírus durante a gestação ou no pós-parto imediato.'},
    'RNRESUL_Z': {'type': 'CHAR (1)', 'description': 'Diagnóstico laboratorial do recém-nascido para Vírus Zika durante a gestação ou no pós-parto imediato.'},
    'RNSO_IGG_Z': {'type': 'CHAR (1)', 'description': 'Resultado do recém-nascido para Sorologia IgG para Zika Vírus durante a gestação ou no pós-parto imediato.'},
    'RNSO_IGM_Z': {'type': 'CHAR (1)', 'description': 'Resultado do recém-nascido para Sorologia IgM para Zika Vírus durante a gestação ou no pós-parto imediato.'},
    'RNTR_IGG_Z': {'type': 'CHAR (1)', 'description': 'Resultado do teste rápido Sorologia IgG do recém-nascido para Zika vírus durante a gestação ou no pós-parto imediato.'},
    'RNTR_IGM_Z': {'type': 'CHAR (1)', 'description': 'Resultado do teste rápido Sorologia IgM do recém-nascido para Zika vírus durante a gestação ou no pós-parto imediato.'},
    'RNPCR_Z': {'type': 'CHAR (1)', 'description': 'Resultado de PCR do recém-nascido para Zika vírus durante a gestação ou no pós-parto imediato'},
    'EXAME_USS': {'type': 'CHAR (1)', 'description': 'Resultado da ultrassonografia realizada durante a gestação.'},
    'DT_USS': {'type': 'CHAR (8)', 'description': 'Data da ultrassonografia realizada durante a gestação'},
    'EXA_TRANSF': {'type': 'CHAR (1)', 'description': 'Resultado de ultrassonografia transfontanela realizada durante a gestação'},
    'DT_TRANSF': {'type': 'CHAR (8)', 'description': 'Data da ultrassonografia transfontanela realizada durante a gestação'},
    'EXAME_TC': {'type': 'CHAR (1)', 'description': 'Resultado de tomografia computadorizada realizada durante a gestação.'},
    'DT_TC': {'type': 'CHAR (8)', 'description': 'Data da tomografia computadorizada realizada durante a gestação.'},
    'EXAME_RS': {'type': 'CHAR (1)', 'description': 'Resultado de ressonância magnética realizada durante a gestação.'},
    'DT_RS': {'type': 'CHAR (8)', 'description': 'Data da ressonância magnética realizada durante a gestação.'},
    'REGIAONOT': {'type': 'CHAR (1)', 'description': 'Macrorregião do local de notificação'},
    'UFNOT': {'type': 'CHAR (2)', 'description': 'Unidade da Federação do local de notificação'},
    'CODMUNNOT': {'type': 'CHAR (6)', 'description': 'Município do local de notificação'},
    'ST_OBITO': {'type': 'CHAR (1)', 'description': 'Evolução para óbito?'},
    'DT_OBITO': {'type': 'CHAR (8)', 'description': 'Data do óbito'},
    'CLASSIFIN': {'type': 'CHAR (1)', 'description': 'Classificação final do caso.'},
    'ETIOLOGIA': {'type': 'CHAR (1)', 'description': 'Etiologia'},
    'CRITERIO': {'type': 'CHAR (7)', 'description': 'Critérios para classificação final do caso'},
    'STATUS_NOT': {'type': 'CHAR (1)', 'description': 'Situação do registro'},
    'DT_ULT_ALT': {'type': 'CHAR (8)', 'description': 'Data da última atualização do registro.'}
}