ab_dict = {
    'AP_MVM': {'type': 'CHAR (6)', 'description': 'Data de Processamento / Movimento (AAAAMM)'},
    'AP_CONDIC': {'type': 'CHAR (2)', 'description': 'Sigla do Tipo de Gestão na qual o Estado ou Município está habilitado'},
    'AP_GESTAO': {'type': 'CHAR (6)', 'description': 'Código da Unidade de Federação + Código Município de Gestão ou UF0000 se a Unidade está sob Gestão Estadual'},
    'AP_CODUNI': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'AP_AUTORIZ': {'type': 'CHAR (13)', 'description': 'Número da APAC. Lei de formação: UFAATsssssssd, onde: UF – Unid. da Federação, AA – ano, T – tipo, sssssss – sequencial, d – dígito'},
    'AP_CMP': {'type': 'CHAR (6)', 'description': 'Data de Atendimento ao paciente / Competência (AAAAMM)'},
    'AP_PRIPAL': {'type': 'CHAR (10)', 'description': 'Procedimento Principal da APAC'},
    'AP_VL_AP': {'type': 'NUMERIC (20.2)', 'description': 'Valor Total da APAC Aprovado'},
    'AP_UFMUN': {'type': 'CHAR (6)', 'description': 'Código da Unidade da Federação + Código do Município do Estabelecimento'},
    'AP_TPUPS': {'type': 'CHAR (2)', 'description': 'Tipo de Estabelecimento'},
    'AP_TIPPRE': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'AP_MN_IND': {'type': 'CHAR (1)', 'description': 'Estabelecimento Mantido / Individual'},
    'AP_CNPJCPF': {'type': 'CHAR (14)', 'description': 'CNPJ do Estabelecimento executante'},
    'AP_CNPJMNT': {'type': 'CHAR (14)', 'description': 'CNPJ MANTENEDORA'},
    'AP_CNSPCN': {'type': 'CHAR (15)', 'description': 'Número do CNS (Cartão Nacional de Saúde) do paciente'},
    'AP_COIDADE': {'type': 'CHAR (1)', 'description': 'Código da Idade'},
    'AP_NUIDADE': {'type': 'CHAR (2)', 'description': 'Número da Idade'},
    'AP_SEXO': {'type': 'CHAR (1)', 'description': 'Sexo do paciente'},
    'AP_RACACOR': {'type': 'CHAR (2)', 'description': 'Raça/Cor do paciente: 01 - Branca, 02 - Preta, 03 - Parda, 04 - Amarela, 05 - Indígena, 99 - Sem informação'},
    'AP_MUNPCN': {'type': 'CHAR (6)', 'description': 'Código da UF + Código do Município de Residência do paciente'},
    'AP_UFNACIO': {'type': 'CHAR (3)', 'description': 'Nacionalidade do paciente'},
    'AP_CEPPCN': {'type': 'CHAR (8)', 'description': 'CEP do paciente'},
    'AP_UFDIF': {'type': 'CHAR (1)', 'description': 'Indica se a UF de residência do paciente é diferente da UF de localização do estabelecimento (N=não, S=sim)'},
    'AP_MNDIF': {'type': 'CHAR (1)', 'description': 'Indica se o município de residência do paciente é diferente do município de localização do estabelecimento (N=não, S=sim)'},
    'AP_DTINIC': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO validade'},
    'AP_DTFIM': {'type': 'CHAR (8)', 'description': 'Data de FIM validade'},
    'AP_TPATEN': {'type': 'CHAR (2)', 'description': 'Tipo de Atendimento de APAC'},
    'AP_TPAPAC': {'type': 'CHAR (1)', 'description': 'Indica se a APAC é 1 - inicial, 2 - continuidade, 3 - única'},
    'AP_MOTSAI': {'type': 'CHAR (2)', 'description': 'Motivo de Saída e Permanência'},
    'AP_OBITO': {'type': 'CHAR (1)', 'description': 'Indicador de Óbito'},
    'AP_ENCERR': {'type': 'CHAR (1)', 'description': 'Indicador de Encerramento'},
    'AP_PERMAN': {'type': 'CHAR (1)', 'description': 'Indicador de Permanência'},
    'AP_ALTA': {'type': 'CHAR (1)', 'description': 'Indicador de Alta'},
    'AP_TRANSF': {'type': 'CHAR (1)', 'description': 'Indicador de Transferência'},
    'AP_DTOCOR': {'type': 'CHAR (8)', 'description': 'Data de Ocorrência que substitui a data de FIM de validade'},
    'AP_CODEMI': {'type': 'CHAR (10)', 'description': 'Código do Órgão emissor'},
    'AP_CATEND': {'type': 'CHAR (2)', 'description': 'Caráter do Atendimento'},
    'AP_APACANT': {'type': 'CHAR (13)', 'description': 'Número APAC Anterior'},
    'AP_UNISOL': {'type': 'CHAR (7)', 'description': 'Código CNES do Estabelecimento Solicitante'},
    'AP_DTSOLIC': {'type': 'CHAR(8)', 'description': 'Data da Solicitação'},
    'AP_DTAUT': {'type': 'CHAR(8)', 'description': 'Data da Autorização'},
    'AP_CIDCAS': {'type': 'CHAR (4)', 'description': 'CID Causas Associadas'},
    'AP_CIDPRI': {'type': 'CHAR (4)', 'description': 'CID Principal'},
    'AP_CIDSEC': {'type': 'CHAR (4)', 'description': 'CID Secundário'},
    'AP_ETNIA': {'type': 'CHAR (4)', 'description': 'Etnia do paciente'},
    'AB_IMC': {'type': 'CHAR (3)', 'description': 'IMC do paciente'},
    'AB_PROCAIH': {'type': 'CHAR (10)', 'description': 'Procedimento do AIH'},
    'AB_DTCIRUR': {'type': 'CHAR (8)', 'description': 'Data da Cirurgia'},
    'AB_NUMAIH': {'type': 'CHAR (13)', 'description': 'Número da AIH'},
    'AB_PRCAIH2': {'type': 'CHAR (10)', 'description': 'Procedimento do AIH'},
    'AB_PRCAIH3': {'type': 'CHAR (10)', 'description': 'Procedimento do AIH'},
    'AB_NUMAIH2': {'type': 'CHAR (13)', 'description': 'Número da AIH'},
    'AB_DTCIRG2': {'type': 'CHAR (8)', 'description': 'Data da Cirurgia'},
    'AB_MESACOM': {'type': 'CHAR (2)', 'description': 'Número em MESES de Acompanhamento'},
    'AB_ANOACOM': {'type': 'CHAR (4)', 'description': 'Ano de Acompanhamento'},
    'AB_PONTBAR': {'type': 'CHAR (1)', 'description': 'Pontuação de Baros12'},
    'AB_TABBARR': {'type': 'CHAR (1)', 'description': 'Tabela de Baros'},
    'AP_NATJUR': {'type': 'CHAR(4)', 'description': 'Código da Natureza Jurídica'}
}


acf_dict = {
    'AP_MVM': {'type': 'CHAR (6)', 'description': 'Data de Processamento / Movimento (AAAAMM)'},
    'AP_CONDIC': {'type': 'CHAR (2)', 'description': 'Sigla do Tipo de Gestão no qual o Estado ou Município está habilitado'},
    'AP_GESTAO': {'type': 'CHAR (6)', 'description': 'Código da Unidade de Federação + Código Município de Gestão ou UF0000 se a Unidade está sob Gestão Estadual'},
    'AP_CODUNI': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'AP_AUTORIZ': {'type': 'CHAR (13)', 'description': 'Número da APAC. Lei de formação: UFAATsssssssd, onde UF – Unid. da Federação, AA – ano, T – tipo, sssssss – sequencial, d – dígito'},
    'AP_CMP': {'type': 'CHAR (6)', 'description': 'Data de Atendimento ao paciente / Competência (AAAAMM)'},
    'AP_PRIPAL': {'type': 'CHAR (10)', 'description': 'Procedimento Principal da APAC'},
    'AP_VL_AP': {'type': 'NUMERIC (20.2)', 'description': 'Valor Total da APAC Aprovado'},
    'AP_UFMUN': {'type': 'CHAR (6)', 'description': 'Código da Unidade da Federação + Código do Município do Estabelecimento'},
    'AP_TPUPS': {'type': 'CHAR (2)', 'description': 'Tipo de Estabelecimento'},
    'AP_TIPPRE': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'AP_MN_IND': {'type': 'CHAR (1)', 'description': 'Estabelecimento Mantido / Individual'},
    'AP_CNPJCPF': {'type': 'CHAR (14)', 'description': 'CNPJ do Estabelecimento executante'},
    'AP_CNPJMNT': {'type': 'CHAR (14)', 'description': 'CNPJ MANTENEDORA'},
    'AP_CNSPCN': {'type': 'CHAR (15)', 'description': 'Número do CNS (Cartão Nacional de Saúde) do paciente'},
    'AP_COIDADE': {'type': 'CHAR (1)', 'description': 'Código da Idade'},
    'AP_NUIDADE': {'type': 'CHAR (2)', 'description': 'Número da Idade'},
    'AP_SEXO': {'type': 'CHAR (1)', 'description': 'Sexo do paciente'},
    'AP_RACACOR': {'type': 'CHAR (2)', 'description': 'Raça/Cor do paciente: 01 - Branca, 02 - Preta, 03 - Parda, 04 - Amarela, 05 - Indígena, 99 - Sem informação'},
    'AP_MUNPCN': {'type': 'CHAR (6)', 'description': 'Código da UF + Código do Município de Residência do paciente'},
    'AP_UFNACIO': {'type': 'CHAR (3)', 'description': 'Nacionalidade do paciente'},
    'AP_CEPPCN': {'type': 'CHAR (8)', 'description': 'CEP do paciente'},
    'AP_UFDIF': {'type': 'CHAR (1)', 'description': 'Indica se a UF de residência do paciente é diferente da UF de localização do estabelecimento (N = não, S = sim)'},
    'AP_MNDIF': {'type': 'CHAR (1)', 'description': 'Indica se o município de residência do paciente é diferente do município de localização do estabelecimento (N = não, S = sim)'},
    'AP_DTINIC': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO validade'},
    'AP_DTFIM': {'type': 'CHAR (8)', 'description': 'Data de FIM validade'},
    'AP_TPATEN': {'type': 'CHAR (2)', 'description': 'Tipo de Atendimento de APAC'},
    'AP_TPAPAC': {'type': 'CHAR (1)', 'description': 'Indica se a APAC é 1 – inicial, 2 – continuidade, 3 – única'},
    'AP_MOTSAI': {'type': 'CHAR (2)', 'description': 'Motivo de Saída e Permanência'},
    'AP_OBITO': {'type': 'CHAR (1)', 'description': 'Indicador de Óbito'},
    'AP_ENCERR': {'type': 'CHAR (1)', 'description': 'Indicador de Encerramento'},
    'AP_PERMAN': {'type': 'CHAR (1)', 'description': 'Indicador de Permanência'},
    'AP_ALTA': {'type': 'CHAR (1)', 'description': 'Indicador de Alta'},
    'AP_TRANSF': {'type': 'CHAR (1)', 'description': 'Indicador de Transferência'},
    'AP_DTOCOR': {'type': 'CHAR (8)', 'description': 'Data de Ocorrência que substitui a data de FIM de validade'},
    'AP_CODEMI': {'type': 'CHAR (10)', 'description': 'Código do Órgão emissor'},
    'AP_CATEND': {'type': 'CHAR (2)', 'description': 'Caráter do Atendimento'},
    'AP_APACANT': {'type': 'CHAR (13)', 'description': 'Número APAC Anterior'},
    'AP_UNISOL': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento Solicitante no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'AP_DTSOLIC': {'type': 'CHAR(8)', 'description': 'Data da Solicitação'},
    'AP_DTAUT': {'type': 'CHAR(8)', 'description': 'Data da Autorização'},
    'AP_CIDCAS': {'type': 'CHAR (4)', 'description': 'CID Causas Associadas'},
    'AP_CIDPRI': {'type': 'CHAR (4)', 'description': 'CID Principal'},
    'AP_CIDSEC': {'type': 'CHAR (4)', 'description': 'CID Secundário'},
    'AP_ETNIA': {'type': 'CHAR (4)', 'description': 'Etnia do paciente'},
    'ACF_DUPLEX': {'type': 'CHAR (1)', 'description': 'Duplex prévio (S - Sim, N - Não)'},
    'ACF_USOCAT': {'type': 'CHAR (1)', 'description': 'Uso do cateter venoso ou outros acessos venosos prévios (S - Sim, N - Não)'},
    'ACF_PREFAV': {'type': 'CHAR (1)', 'description': 'FAV prévia (S - Sim, N - Não)'},
    'ACF_FLEBIT': {'type': 'CHAR (1)', 'description': 'Flebites (S - Sim, N - Não)'},
    'ACF_HEMATO': {'type': 'CHAR (1)', 'description': 'Hematomas (S - Sim, N - Não)'},
    'ACF_VEIAVI': {'type': 'CHAR (1)', 'description': 'Veia visível (S - Sim, N - Não)'},
    'ACF_PULSO': {'type': 'CHAR (1)', 'description': 'Presença de pulso (S - Sim, N - Não)'},
    'ACF_VEIDIA': {'type': 'NUMERIC (4)', 'description': 'Diâmetro da veia (em mm)'},
    'ACF_ARTDIA': {'type': 'NUMERIC (4)', 'description': 'Diâmetro da artéria (em mm)'},
    'ACF_FREMIT': {'type': 'CHAR(1)', 'description': 'Frêmito - Vibração perceptível pelo tato'},
    'AP_NATJUR': {'type': 'CHAR(4)', 'description': 'Código da Natureza Jurídica'}
}


ad_dict = {
    'AP_MVM': {'type': 'CHAR (6)', 'description': 'Data de Processamento / Movimento (AAAAMM)'},
    'AP_CONDIC': {'type': 'CHAR (2)', 'description': 'Sigla do Tipo de Gestão no qual o Estado ou Município está habilitado'},
    'AP_GESTAO': {'type': 'CHAR (6)', 'description': 'Cód. da Unidade de Federação + Cód. Município de Gestão, ou UF0000 se a Unidade está sob Gestão Estadual'},
    'AP_CODUNI': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'AP_AUTORIZ': {'type': 'CHAR (13)', 'description': 'Número da APAC. Lei de formação: UFAATsssssssd, onde UF – Unid. da Federação, AA – ano, T – tipo, sssssss – sequencial, d – dígito'},
    'AP_CMP': {'type': 'CHAR (6)', 'description': 'Data de Atendimento ao paciente / Competência (AAAAMM)'},
    'AP_PRIPAL': {'type': 'CHAR (10)', 'description': 'Procedimento Principal da APAC'},
    'AP_VL_AP': {'type': 'NUMERIC (20.2)', 'description': 'Valor Total da APAC Aprovado'},
    'AP_UFMUN': {'type': 'CHAR (6)', 'description': 'Código da Unidade da Federação + Município do Estabelecimento'},
    'AP_TPUPS': {'type': 'CHAR (2)', 'description': 'Tipo de Estabelecimento'},
    'AP_TIPPRE': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'AP_MN_IND': {'type': 'CHAR (1)', 'description': 'Estabelecimento Mantido / Individual'},
    'AP_CNPJCPF': {'type': 'CHAR (14)', 'description': 'CNPJ do Estabelecimento executante'},
    'AP_CNPJMNT': {'type': 'CHAR (14)', 'description': 'CNPJ da Mantenedora do estabelecimento ou zeros, caso não a tenha'},
    'AP_CNSPCN': {'type': 'CHAR (15)', 'description': 'Número do CNS (Cartão Nacional de Saúde) do paciente'},
    'AP_COIDADE': {'type': 'CHAR (1)', 'description': 'Código da Idade do paciente'},
    'AP_NUIDADE': {'type': 'CHAR (2)', 'description': 'Número da Idade'},
    'AP_SEXO': {'type': 'CHAR (1)', 'description': 'Sexo do paciente'},
    'AP_RACACOR': {'type': 'CHAR (2)', 'description': 'Raça/Cor do paciente: 01 - Branca, 02 - Preta, 03 - Parda, 04 - Amarela, 05 - Indígena, 99 - Sem informação'},
    'AP_MUNPCN': {'type': 'CHAR (6)', 'description': 'Código da Unidade de Federação + Código Município de Residência do paciente'},
    'AP_UFNACIO': {'type': 'CHAR (3)', 'description': 'Código da Nacionalidade do paciente'},
    'AP_CEPPCN': {'type': 'CHAR (8)', 'description': 'CEP do endereço do paciente'},
    'AP_UFDIF': {'type': 'CHAR (1)', 'description': 'Indica se a UF de residência do paciente é diferente da UF de localização do estabelecimento: 0 = mesma UF; 1 = UF diferente'},
    'AP_MNDIF': {'type': 'CHAR (1)', 'description': 'Indica se o município de residência do paciente é diferente do município de localização do estabelecimento: 0 = mesmo município; 1 = município diferente'},
    'AP_DTINIC': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO validade (AAAAMMDD)'},
    'AP_DTFIM': {'type': 'CHAR (8)', 'description': 'Data de FIM validade (AAAAMMDD)'},
    'AP_TPATEN': {'type': 'CHAR (2)', 'description': 'Tipo de Atendimento de APAC'},
    'AP_TPAPAC': {'type': 'CHAR (1)', 'description': 'Indica se a APAC é 1 - inicial, 2 - continuidade, 3 - única'},
    'AP_MOTSAI': {'type': 'CHAR (2)', 'description': 'Motivo de Saída e Permanência'},
    'AP_OBITO': {'type': 'CHAR (1)', 'description': 'Indicador de Óbito'},
    'AP_ENCERR': {'type': 'CHAR (1)', 'description': 'Indicador de Encerramento'},
    'AP_PERMAN': {'type': 'CHAR (1)', 'description': 'Indicador de Permanência'},
    'AP_ALTA': {'type': 'CHAR (1)', 'description': 'Indicador de Alta'},
    'AP_TRANSF': {'type': 'CHAR (1)', 'description': 'Indicador de Transferência'},
    'AP_DTOCOR': {'type': 'CHAR (8)', 'description': 'Data de Ocorrência que substitui a data de FIM de validade'},
    'AP_CODEMI': {'type': 'CHAR (10)', 'description': 'Código do Órgão emissor'},
    'AP_CATEND': {'type': 'CHAR (2)', 'description': 'Caráter do Atendimento'},
    'AP_APACANT': {'type': 'CHAR (13)', 'description': 'Número APAC Anterior'},
    'AP_UNISOL': {'type': 'CHAR (7)', 'description': 'Código CNES do Estabelecimento Solicitante'},
    'AP_DTSOLIC': {'type': 'CHAR(8)', 'description': 'Data da Solicitação (AAAAMMDD)'},
    'AP_DTAUT': {'type': 'CHAR(8)', 'description': 'Data da Autorização (AAAAMMDD)'},
    'AP_CIDCAS': {'type': 'CHAR (4)', 'description': 'CID Causas Associadas'},
    'AP_CIDPRI': {'type': 'CHAR (4)', 'description': 'CID Principal'},
    'AP_CIDSEC': {'type': 'CHAR (4)', 'description': 'CID Secundário'},
    'AP_ETNIA': {'type': 'CHAR (4)', 'description': 'Etnia do paciente'}
}


am_dict = {
    'AP_MVM': {'type': 'CHAR (6)', 'description': 'Data de Processamento / Movimento (AAAAMM)'},
    'AP_CONDIC': {'type': 'CHAR (2)', 'description': 'Sigla do Tipo de Gestão na qual Estado ou Município está habilitado'},
    'AP_GESTAO': {'type': 'CHAR (6)', 'description': 'Código da Unidade de Federação + Código do Município de Gestão, ou UF0000 se o estabelecimento está sob Gestão Estadual'},
    'AP_CODUNI': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'AP_AUTORIZ': {'type': 'CHAR (13)', 'description': 'Número da APAC. Lei de formação: UFAATsssssssd, onde UF – Unid. da Federação, AA – ano, T – tipo, sssssss – sequencial, d – dígito'},
    'AP_CMP': {'type': 'CHAR (6)', 'description': 'Data de Atendimento ao paciente / Competência (AAAAMM)'},
    'AP_PRIPAL': {'type': 'CHAR (10)', 'description': 'Procedimento Principal da APAC'},
    'AP_VL_AP': {'type': 'NUMERIC (12.2)', 'description': 'Valor Total da APAC Aprovado'},
    'AP_UFMUN': {'type': 'CHAR (6)', 'description': 'Código da Unidade da Federação + Código do Município do Estabelecimento'},
    'AP_TPUPS': {'type': 'CHAR (2)', 'description': 'Tipo de Estabelecimento'},
    'AP_TIPPRE': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'AP_MN_IND': {'type': 'CHAR (1)', 'description': 'Estabelecimento Mantido / Individual'},
    'AP_CNPJCPF': {'type': 'CHAR (14)', 'description': 'CNPJ do Estabelecimento executante'},
    'AP_CNPJMNT': {'type': 'CHAR (14)', 'description': 'CNPJ Mantenedora'},
    'AP_CNSPCN': {'type': 'CHAR (15)', 'description': 'Número do CNS (Cartão Nacional de Saúde) do paciente'},
    'AP_COIDADE': {'type': 'CHAR (1)', 'description': 'Código da Idade do paciente'},
    'AP_NUIDADE': {'type': 'CHAR (2)', 'description': 'Número da Idade'},
    'AP_SEXO': {'type': 'CHAR (1)', 'description': 'Sexo do paciente'},
    'AP_RACACOR': {'type': 'CHAR (2)', 'description': 'Raça/Cor do paciente: 01 - Branca, 02 - Preta, 03 - Parda, 04 - Amarela, 05 - Indígena, 99 - Sem informação'},
    'AP_MUNPCN': {'type': 'CHAR (6)', 'description': 'Código Unidade de Federação + Código do Município de Residência do paciente'},
    'AP_UFNACIO': {'type': 'CHAR (3)', 'description': 'Código da Nacionalidade do paciente'},
    'AP_CEPPCN': {'type': 'CHAR (8)', 'description': 'CEP do paciente'},
    'AP_UFDIF': {'type': 'CHAR (2)', 'description': 'Indica se a UF de residência do paciente é diferente da UF de localização do estabelecimento'},
    'AP_MNDIF': {'type': 'CHAR (2)', 'description': 'Indica se o município de residência do paciente é diferente do município de localização do estabelecimento'},
    'AP_DTINIC': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO validade'},
    'AP_DTFIM': {'type': 'CHAR (8)', 'description': 'Data de FIM validade'},
    'AP_TPATEN': {'type': 'CHAR (2)', 'description': 'Tipo de Atendimento de APAC'},
    'AP_TPAPAC': {'type': 'CHAR (1)', 'description': 'Indica se a APAC é 1 - inicial, 2 - continuidade, 3 – única'},
    'AP_MOTSAI': {'type': 'CHAR (2)', 'description': 'Motivo de Saída e Permanência'},
    'AP_OBITO': {'type': 'CHAR (1)', 'description': 'Indicador de Óbito'},
    'AP_ENCERR': {'type': 'CHAR (1)', 'description': 'Indicador de Encerramento'},
    'AP_PERMAN': {'type': 'CHAR (1)', 'description': 'Indicador de Permanência'},
    'AP_ALTA': {'type': 'CHAR (1)', 'description': 'Indicador de Alta'},
    'AP_TRANSF': {'type': 'CHAR (1)', 'description': 'Indicador de Transferência'},
    'AP_DTOCOR': {'type': 'CHAR (8)', 'description': 'Data de Ocorrência que substitui a data de FIM de validade'},
    'AP_CODEMI': {'type': 'CHAR (10)', 'description': 'Código do Órgão emissor'},
    'AP_CATEND': {'type': 'CHAR (2)', 'description': 'Caráter do Atendimento'},
    'AP_APACANT': {'type': 'CHAR (13)', 'description': 'Número APAC Anterior'},
    'AP_UNISOL': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento solicitante no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'AP_DTSOLIC': {'type': 'CHAR(8)', 'description': 'Data da Solicitação'},
    'AP_DTAUT': {'type': 'CHAR(8)', 'description': 'Data da Autorização'},
    'AP_CIDCAS': {'type': 'CHAR (4)', 'description': 'CID Causas Associadas'},
    'AP_CIDPRI': {'type': 'CHAR (4)', 'description': 'CID Principal'},
    'AP_CIDSEC': {'type': 'CHAR (4)', 'description': 'CID Secundário'},
    'AP_ETNIA': {'type': 'CHAR (4)', 'description': 'Etnia do paciente'},
    'AM_PESO': {'type': 'CHAR (3)', 'description': 'Peso do paciente em kg'},
    'AM_ALTURA': {'type': 'CHAR (3)', 'description': 'Altura do paciente em cm'},
    'AM_TRANSPL': {'type': 'CHAR (1)', 'description': 'Indicador se o paciente fez transplante'},
    'AM_QTDTRAN': {'type': 'CHAR (2)', 'description': 'Quantidade de Transplantes'},
    'AM_GESTANT': {'type': 'CHAR (1)', 'description': 'Indicador de Gestante (S = Sim; N = Não)'}
}


an_dict = {
    'AP_MVM': {'type': 'CHAR (6)', 'description': 'Data de Processamento / Movimento (AAAAMM)'},
    'AP_CONDIC': {'type': 'CHAR (2)', 'description': 'Sigla do Tipo de Gestão no qual o Estado ou Município está habilitado'},
    'AP_GESTAO': {'type': 'CHAR (6)', 'description': 'Código da Unidade de Federação + Código Município de Gestão ou UF0000 se a Unidade está sob Gestão Estadual'},
    'AP_CODUNI': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'AP_AUTORIZ': {'type': 'CHAR (13)', 'description': 'Número da APAC. Lei de formação: UFAATsssssssd, onde UF – Unid. da Federação, AA – ano, T – tipo, sssssss – sequencial, d – dígito'},
    'AP_CMP': {'type': 'CHAR (6)', 'description': 'Data de Atendimento ao paciente / Competência (AAAAMM)'},
    'AP_PRIPAL': {'type': 'CHAR (10)', 'description': 'Procedimento Principal da APAC'},
    'AP_VL_AP': {'type': 'NUMERIC (20.2)', 'description': 'Valor Total da APAC Aprovado'},
    'AP_UFMUN': {'type': 'CHAR (6)', 'description': 'Código de Unidade da Federação + Código do Município do Estabelecimento'},
    'AP_TPUPS': {'type': 'CHAR (2)', 'description': 'Tipo de Estabelecimento'},
    'AP_TIPPRE': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'AP_MN_IND': {'type': 'CHAR (1)', 'description': 'Estabelecimento Mantido / Individual'},
    'AP_CNPJCPF': {'type': 'CHAR (14)', 'description': 'CNPJ do Estabelecimento executante'},
    'AP_CNPJMNT': {'type': 'CHAR (14)', 'description': 'CNPJ MANTENEDORA'},
    'AP_CNSPCN': {'type': 'CHAR (15)', 'description': 'Número do CNS (Cartão Nacional de Saúde) do paciente'},
    'AP_COIDADE': {'type': 'CHAR (1)', 'description': 'Código da Idade'},
    'AP_NUIDADE': {'type': 'CHAR (2)', 'description': 'Número da Idade'},
    'AP_SEXO': {'type': 'CHAR (1)', 'description': 'Sexo do paciente'},
    'AP_RACACOR': {'type': 'CHAR (2)', 'description': 'Raça/Cor do paciente: 01 - Branca, 02 - Preta, 03 - Parda, 04 - Amarela, 05 - Indígena, 99 - Sem informação'},
    'AP_MUNPCN': {'type': 'CHAR (6)', 'description': 'Código da UF + Código do Município de Residência do paciente'},
    'AP_UFNACIO': {'type': 'CHAR (3)', 'description': 'Nacionalidade do paciente'},
    'AP_CEPPCN': {'type': 'CHAR (8)', 'description': 'CEP do paciente'},
    'AP_UFDIF': {'type': 'CHAR (1)', 'description': 'Indica se a UF de residência do paciente é diferente da UF de localização do estabelecimento (N = não, S = sim)'},
    'AP_MNDIF': {'type': 'CHAR (1)', 'description': 'Indica se o município de residência do paciente é diferente do município de localização do estabelecimento (N = não, S = sim)'},
    'AP_DTINIC': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO validade'},
    'AP_DTFIM': {'type': 'CHAR (8)', 'description': 'Data de FIM validade'},
    'AP_TPATEN': {'type': 'CHAR (2)', 'description': 'Tipo de Atendimento de APAC'},
    'AP_TPAPAC': {'type': 'CHAR (1)', 'description': 'Indica se a APAC é 1 - inicial, 2 - continuidade, 3 - única'},
    'AP_MOTSAI': {'type': 'CHAR (2)', 'description': 'Motivo de Saída e Permanência'},
    'AP_OBITO': {'type': 'CHAR (1)', 'description': 'Indicador de Óbito'},
    'AP_ENCERR': {'type': 'CHAR (1)', 'description': 'Indicador de Encerramento'},
    'AP_PERMAN': {'type': 'CHAR (1)', 'description': 'Indicador de Permanência'},
    'AP_ALTA': {'type': 'CHAR (1)', 'description': 'Indicador de Alta'},
    'AP_TRANSF': {'type': 'CHAR (1)', 'description': 'Indicador de Transferência'},
    'AP_DTOCOR': {'type': 'CHAR (8)', 'description': 'Data de Ocorrência que substitui a data de FIM de validade'},
    'AP_CODEMI': {'type': 'CHAR (10)', 'description': 'Código do Órgão emissor'},
    'AP_CATEND': {'type': 'CHAR (2)', 'description': 'Caráter do Atendimento'},
    'AP_APACANT': {'type': 'CHAR (13)', 'description': 'Número APAC Anterior'},
    'AP_UNISOL': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento solicitante no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'AP_DTSOLIC': {'type': 'CHAR(8)', 'description': 'Data da Solicitação'},
    'AP_DTAUT': {'type': 'CHAR(8)', 'description': 'Data da Autorização'},
    'AP_CIDCAS': {'type': 'CHAR (4)', 'description': 'CID Causas Associadas'},
    'AP_CIDPRI': {'type': 'CHAR (4)', 'description': 'CID Principal'},
    'AP_CIDSEC': {'type': 'CHAR (4)', 'description': 'CID Secundário'},
    'AP_ETNIA': {'type': 'CHAR (4)', 'description': 'Etnia do paciente'},
    'AN_DTPDR': {'type': 'CHAR (8)', 'description': 'Data (AAAAMMDD) da PRIMEIRA diálise realizada'},
    'AN_ALTURA': {'type': 'CHAR (3)', 'description': 'Altura do paciente em cm'},
    'AN_PESO': {'type': 'CHAR (3)', 'description': 'Peso do paciente em kg'},
    'AN_DIURES': {'type': 'CHAR (4)', 'description': 'Diurese em ml'},
    'AN_GLICOS': {'type': 'CHAR (4)', 'description': 'Glicose em Mg/dl'},
    'AN_ACEVAS': {'type': 'CHAR (1)', 'description': 'Acesso Vascular (S = Sim; N = Não)'},
    'AN_ULSOAB': {'type': 'CHAR (1)', 'description': 'Ultrassonografia Abdominal (S = Sim; N = Não)'},
    'AN_TRU': {'type': 'CHAR (4)', 'description': 'TRU (taxa de redução de ureia)'},
    'AN_INTFIS': {'type': 'CHAR (2)', 'description': 'Quantidade de intervenção de Fístula'},
    'AN_CNCDO': {'type': 'CHAR (1)', 'description': 'Inscrito na lista da CNCDO (S = Sim; N = Não)'},
    'AN_ALBUMI': {'type': 'CHAR (2)', 'description': 'Albumina em g%'},
    'AN_HCV': {'type': 'CHAR (1)', 'description': 'Indicativo de presença de Anticorpos de HCV (P = Positivo; N = Negativo)'},
    'AN_HBSAG': {'type': 'CHAR (1)', 'description': 'Indicativo de HBsAg (P = Positivo; N = Negativo)'}
}


aq_dict = {
    'AP_MVM': {'type': 'CHAR (6)', 'description': 'Data de Processamento / Movimento (AAAAMM)'},
    'AP_CONDIC': {'type': 'CHAR (2)', 'description': 'Sigla do Tipo de Gestão no qual o Estado ou Município está habilitado'},
    'AP_GESTAO': {'type': 'CHAR (6)', 'description': 'Código da Unidade de Federação + Código Município de Gestão ou UF0000 se a Unidade está sob Gestão Estadual'},
    'AP_CODUNI': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'AP_AUTORIZ': {'type': 'CHAR (13)', 'description': 'Número da APAC. Lei de formação: UFAATsssssssd, onde UF – Unid. da Federação, AA – ano, T – tipo, sssssss – sequencial, d – dígito'},
    'AP_CMP': {'type': 'CHAR (6)', 'description': 'Data de Atendimento ao paciente / Competência (AAAAMM)'},
    'AP_PRIPAL': {'type': 'CHAR (10)', 'description': 'Procedimento Principal da APAC'},
    'AP_VL_AP': {'type': 'NUMERIC (12.2)', 'description': 'Valor Total da APAC Aprovado'},
    'AP_UFMUN': {'type': 'CHAR (6)', 'description': 'Código da Unidade da Federação + Código do Município do Estabelecimento'},
    'AP_TPUPS': {'type': 'CHAR (2)', 'description': 'Tipo de Estabelecimento'},
    'AP_TIPPRE': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'AP_MN_IND': {'type': 'CHAR (1)', 'description': 'Estabelecimento Mantido / Individual'},
    'AP_CNPJCPF': {'type': 'CHAR (14)', 'description': 'CNPJ do Estabelecimento executante'},
    'AP_CNPJMNT': {'type': 'CHAR (14)', 'description': 'CNPJ MANTENEDORA'},
    'AP_CNSPCN': {'type': 'CHAR (15)', 'description': 'Número do CNS (Cartão Nacional de Saúde) do paciente'},
    'AP_COIDADE': {'type': 'CHAR (1)', 'description': 'Código da Idade'},
    'AP_NUIDADE': {'type': 'CHAR (2)', 'description': 'Número da Idade'},
    'AP_SEXO': {'type': 'CHAR (1)', 'description': 'Sexo do paciente'},
    'AP_RACACOR': {'type': 'CHAR (2)', 'description': 'Raça/Cor do paciente: 01 - Branca, 02 - Preta, 03 - Parda, 04 - Amarela, 05 - Indígena, 99 - Sem informação'},
    'AP_MUNPCN': {'type': 'CHAR (6)', 'description': 'Código da UF + Código do Município de Residência do paciente'},
    'AP_UFNACIO': {'type': 'CHAR (3)', 'description': 'Nacionalidade do paciente'},
    'AP_CEPPCN': {'type': 'CHAR (8)', 'description': 'CEP do paciente'},
    'AP_UFDIF': {'type': 'CHAR (1)', 'description': 'Indica se a UF de residência do paciente é diferente da UF de localização do estabelecimento (N = não, S = sim)'},
    'AP_MNDIF': {'type': 'CHAR (1)', 'description': 'Indica se o município de residência do paciente é diferente do município de localização do estabelecimento (N = não, S = sim)'},
    'AP_DTINIC': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO validade'},
    'AP_DTFIM': {'type': 'CHAR (8)', 'description': 'Data de FIM validade'},
    'AP_TPATEN': {'type': 'CHAR (2)', 'description': 'Tipo de Atendimento de APAC'},
    'AP_TPAPAC': {'type': 'CHAR (1)', 'description': 'Indica se a APAC é 1 - inicial, 2 - continuidade, 3 - única'},
    'AP_MOTSAI': {'type': 'CHAR (2)', 'description': 'Motivo de Saída e Permanência'},
    'AP_OBITO': {'type': 'CHAR (1)', 'description': 'Indicador de Óbito'},
    'AP_ENCERR': {'type': 'CHAR (1)', 'description': 'Indicador de Encerramento'},
    'AP_PERMAN': {'type': 'CHAR (1)', 'description': 'Indicador de Permanência'},
    'AP_ALTA': {'type': 'CHAR (1)', 'description': 'Indicador de Alta'},
    'AP_TRANSF': {'type': 'CHAR (1)', 'description': 'Indicador de Transferência'},
    'AP_DTOCOR': {'type': 'CHAR (8)', 'description': 'Data de Ocorrência que substitui a data de FIM de validade'},
    'AP_CODEMI': {'type': 'CHAR (10)', 'description': 'Código do Órgão emissor'},
    'AP_CATEND': {'type': 'CHAR (2)', 'description': 'Caráter do Atendimento'},
    'AP_APACANT': {'type': 'CHAR (13)', 'description': 'Número APAC Anterior'},
    'AP_UNISOL': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento solicitante no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'AP_DTSOLIC': {'type': 'CHAR(8)', 'description': 'Data da Solicitação'},
    'AP_DTAUT': {'type': 'CHAR(8)', 'description': 'Data da Autorização'},
    'AP_CIDCAS': {'type': 'CHAR (4)', 'description': 'CID Causas Associadas'},
    'AP_CIDPRI': {'type': 'CHAR (4)', 'description': 'CID Principal'},
    'AP_CIDSEC': {'type': 'CHAR (4)', 'description': 'CID Secundário'},
    'AP_ETNIA': {'type': 'CHAR (4)', 'description': 'Etnia do paciente'},
    'AQ_CID10': {'type': 'CHAR (4)', 'description': 'CID 10 – Topografia'},
    'AQ_LINFIN': {'type': 'CHAR (1)', 'description': 'Linfonodos regionais invadidos (S = Sim; N = Não; 3 = Não Avaliáveis)'},
    'AQ_ESTADI': {'type': 'CHAR (1)', 'description': 'Estádio - UICC (0; 1; 2; 3; 4)'},
    'AQ_GRAHIS': {'type': 'CHAR (2)', 'description': 'Grau Histopatológico'},
    'AQ_DTIDEN': {'type': 'CHAR (8)', 'description': 'Data da identificação patológica do caso (AAAAMMDD)'},
    'AQ_TRANTE': {'type': 'CHAR (1)', 'description': 'Tratamentos anteriores (S = Sim; N = Não)'},
    'AQ_CIDINI1': {'type': 'CHAR (4)', 'description': 'CID 1º Tratamento anterior'},
    'AQ_DTINI1': {'type': 'CHAR (8)', 'description': 'Data de início (AAAAMMDD) 1º tratamento anterior'},
    'AQ_CIDINI2': {'type': 'CHAR (4)', 'description': 'CID 2º Tratamento anterior'},
    'AQ_DTINI2': {'type': 'CHAR (8)', 'description': 'Data de início (AAAAMMDD) 2º tratamento anterior'},
    'AQ_CIDINI3': {'type': 'CHAR (4)', 'description': 'CID 3º Tratamento anterior'},
    'AQ_DTINI3': {'type': 'CHAR (8)', 'description': 'Data de início (AAAAMMDD) 3º tratamento anterior'},
    'AQ_CONTTR': {'type': 'CHAR (1)', 'description': 'Continuidade do tratamento (S = Sim; N = Não)'},
    'AQ_DTINTR': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO do tratamento solicitado (AAAAMMDD)'},
    'AQ_ESQU_P1': {'type': 'CHAR (5)', 'description': 'ESQUEMA (Sigla ou abrev.) - 5 primeiras posições'},
    'AQ_TOTMPL': {'type': 'CHAR (3)', 'description': 'Total de MESES Planejados'},
    'AQ_TOTMAU': {'type': 'CHAR (3)', 'description': 'Total de MESES Autorizados'},
    'AQ_ESQU_P2': {'type': 'CHAR (10)', 'description': 'ESQUEMA (Sigla ou abrev.) - 10 últimas posições'},
    'AP_NATJUR': {'type': 'CHAR (4)', 'description': 'Código da Natureza Jurídica'}
}


ar_dict = {
    'AP_MVM': {'type': 'CHAR (6)', 'description': 'Data de Processamento / Movimento (AAAAMM)'},
    'AP_CONDIC': {'type': 'CHAR (2)', 'description': 'Sigla do Tipo de Gestão no qual o Estado ou Município está habilitado'},
    'AP_GESTAO': {'type': 'CHAR (6)', 'description': 'Código da Unidade de Federação + Código Município de Gestão ou UF0000 se a Unidade está sob Gestão Estadual'},
    'AP_CODUNI': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'AP_AUTORIZ': {'type': 'CHAR (13)', 'description': 'Número da APAC. Lei de formação: UFAATsssssssd, onde: UF – Unid. da Federação, AA – ano, T – tipo, sssssss – sequencial, d – dígito'},
    'AP_CMP': {'type': 'CHAR (6)', 'description': 'Data de Atendimento ao paciente / Competência (AAAAMM)'},
    'AP_PRIPAL': {'type': 'CHAR (10)', 'description': 'Procedimento Principal da APAC'},
    'AP_VL_AP': {'type': 'NUMERIC (20.2)', 'description': 'Valor Total da APAC Aprovado'},
    'AP_UFMUN': {'type': 'CHAR (6)', 'description': 'Código da Unidade da Federação + Código do Município do Estabelecimento'},
    'AP_TPUPS': {'type': 'CHAR (2)', 'description': 'Tipo de Estabelecimento'},
    'AP_TIPPRE': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'AP_MN_IND': {'type': 'CHAR (1)', 'description': 'Estabelecimento Mantido / Individual'},
    'AP_CNPJCPF': {'type': 'CHAR (14)', 'description': 'CNPJ do Estabelecimento executante'},
    'AP_CNPJMNT': {'type': 'CHAR (14)', 'description': 'CNPJ MANTENEDORA'},
    'AP_CNSPCN': {'type': 'CHAR (15)', 'description': 'Número do CNS (Cartão Nacional de Saúde) do paciente'},
    'AP_COIDADE': {'type': 'CHAR (1)', 'description': 'Código da Idade'},
    'AP_NUIDADE': {'type': 'CHAR (2)', 'description': 'Número da Idade'},
    'AP_SEXO': {'type': 'CHAR (1)', 'description': 'Sexo do paciente'},
    'AP_RACACOR': {'type': 'CHAR (2)', 'description': 'Raça/Cor do paciente: 01 - Branca, 02 - Preta, 03 - Parda, 04 - Amarela, 05 - Indígena, 99 - Sem informação'},
    'AP_MUNPCN': {'type': 'CHAR (6)', 'description': 'Código da UF + Código do Município de Residência do paciente'},
    'AP_UFNACIO': {'type': 'CHAR (3)', 'description': 'Nacionalidade do paciente'},
    'AP_CEPPCN': {'type': 'CHAR (8)', 'description': 'CEP do paciente'},
    'AP_UFDIF': {'type': 'CHAR (2)', 'description': 'Indica se a UF de residência do paciente é diferente da UF de localização do estabelecimento (N = não, S = sim)'},
    'AP_MNDIF': {'type': 'CHAR (1)', 'description': 'Indica se o município de residência do paciente é diferente do município de localização do estabelecimento (N = não, S = sim)'},
    'AP_DTINIC': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO validade'},
    'AP_DTFIM': {'type': 'CHAR (8)', 'description': 'Data de FIM validade'},
    'AP_TPATEN': {'type': 'CHAR (2)', 'description': 'Tipo de Atendimento de APAC'},
    'AP_TPAPAC': {'type': 'CHAR (1)', 'description': 'Indica se a APAC é 1 - inicial, 2 - continuidade, 3 - única'},
    'AP_MOTSAI': {'type': 'CHAR (2)', 'description': 'Motivo de Saída e Permanência'},
    'AP_OBITO': {'type': 'CHAR (1)', 'description': 'Indicador de Óbito'},
    'AP_ENCERR': {'type': 'CHAR (1)', 'description': 'Indicador de Encerramento'},
    'AP_PERMAN': {'type': 'CHAR (1)', 'description': 'Indicador de Permanência'},
    'AP_ALTA': {'type': 'CHAR (1)', 'description': 'Indicador de Alta'},
    'AP_TRANSF': {'type': 'CHAR (1)', 'description': 'Indicador de Transferência'},
    'AP_DTOCOR': {'type': 'CHAR (8)', 'description': 'Data de Ocorrência que substitui a data de FIM de validade'},
    'AP_CODEMI': {'type': 'CHAR (10)', 'description': 'Código do Órgão emissor'},
    'AP_CATEND': {'type': 'CHAR (2)', 'description': 'Caráter do Atendimento'},
    'AP_APACANT': {'type': 'CHAR (13)', 'description': 'Número APAC Anterior'},
    'AP_UNISOL': {'type': 'CHAR (7)', 'description': 'Código CNES do Estabelecimento Solicitante'},
    'AP_DTSOLIC': {'type': 'CHAR (8)', 'description': 'Data da Solicitação'},
    'AP_DTAUT': {'type': 'CHAR (8)', 'description': 'Data da Autorização'},
    'AP_CIDCAS': {'type': 'CHAR (4)', 'description': 'CID Causas Associadas'},
    'AP_CIDPRI': {'type': 'CHAR (4)', 'description': 'CID Principal'},
    'AP_CIDSEC': {'type': 'CHAR (4)', 'description': 'CID Secundário'},
    'AP_ETNIA': {'type': 'CHAR (4)', 'description': 'Etnia do paciente'},
    'AR_SMRD': {'type': 'CHAR (3)', 'description': ''},
    'AR_CID10': {'type': 'CHAR (4)', 'description': 'CID-10 - Topografia'},
    'AR_LINFIN': {'type': 'CHAR (1)', 'description': 'Linfonodos regionais invadidos (S = Sim; N =Não; 3= Não Avaliáveis)'},
    'AR_ESTADI': {'type': 'CHAR (1)', 'description': 'Estádio - UICC (0; 1; 2; 3; 4)'},
    'AR_GRAHIS': {'type': 'CHAR (2)', 'description': 'Grau Histopatológico'},
    'AR_DTIDEN': {'type': 'CHAR (8)', 'description': 'Data da identificação patológica do caso (AAAAMMDD)'},
    'AR_TRANTE': {'type': 'CHAR (1)', 'description': 'Tratamentos anteriores (S = Sim; N = Não)'},
    'AR_CIDINI1': {'type': 'CHAR (4)', 'description': 'CID 1º Tratamento anterior'},
    'AR_DTINI1': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO (AAAAMMDD) 1º tratamento anterior'},
    'AR_CIDINI2': {'type': 'CHAR (4)', 'description': 'CID 2º Tratamento anterior'},
    'AR_DTINI2': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO (AAAAMMDD) 2º tratamento anterior'},
    'AR_CIDINI3': {'type': 'CHAR (4)', 'description': 'CID 3º Tratamento anterior'},
    'AR_DTINI3': {'type': 'CHAR (8)', 'description': 'Data de início (AAAAMMDD) 3º tratamento anterior'},
    'AR_CONTTR': {'type': 'CHAR (1)', 'description': 'Continuidade do tratamento (S = Sim; N = Não)'},
    'AR_DTINTR': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO do tratamento solicitado (AAAAMMDD)'},
    'AR_FINALI': {'type': 'CHAR (1)', 'description': 'Finalidade do Tratamento: (1 = RADICAL; 2 = ADJUVANTE; 3 = ANTIÁLGICA; 4 = PALIATIVA; 5 = PRÉVIA; 6 = ANTIHEMORRÁGICA)'},
    'AR_CIDTR1': {'type': 'CHAR (4)', 'description': 'CID Topográfico 1º'},
    'AR_CIDTR2': {'type': 'CHAR (4)', 'description': 'CID Topográfico 2º'},
    'AR_CIDTR3': {'type': 'CHAR (4)', 'description': 'CID Topográfico 3º'},
    'AR_NUMC1': {'type': 'CHAR (3)', 'description': 'Nº Campo/Inserções 1º'},
    'AR_INIAR1': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO 1º (AAAAMMDD)'},
    'AR_INIAR2': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO 2º (AAAAMMDD)'},
    'AR_INIAR3': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO 3º (AAAAMMDD)'},
    'AR_FIMAR1': {'type': 'CHAR (8)', 'description': 'Data de Fim 1º (AAAAMMDD)'},
    'AR_FIMAR2': {'type': 'CHAR (8)', 'description': 'Data de FIM 2º (AAAAMMDD)'},
    'AR_FIMAR3': {'type': 'CHAR (8)', 'description': 'Data de Fim 3º (AAAAMMDD)'},
    'AR_NUMC2': {'type': 'CHAR (3)', 'description': 'Nº Campo/Inserções 2º'},
    'AR_NUMC3': {'type': 'CHAR (3)', 'description': 'Nº Campo/Inserções 3º'},
    'AP_NATJUR': {'type': 'CHAR (4)', 'description': 'Código da Natureza Jurídica'}
}


pa_dict = {
    'PA_CODUNI': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'PA_GESTAO': {'type': 'CHAR (6)', 'description': 'Código da Unidade da Federação7 (IBGE) + Código do Município (IBGE) do Gestor, ou UF0000 se o estabelecimento estiver sob Gestão Estadual'},
    'PA_CONDIC': {'type': 'CHAR (2)', 'description': 'Sigla do Tipo de Gestão no qual o Estado ou Município está habilitado'},
    'PA_UFMUN': {'type': 'CHAR (6)', 'description': 'Unidade da Federação + Código do Município onde está localizado o estabelecimento'},
    'PA_REGCT': {'type': 'CHAR (4)', 'description': 'Código da Regra Contratual'},
    'PA_INCOUT': {'type': 'CHAR (4)', 'description': 'Incremento Outros'},
    'PA_INCURG': {'type': 'CHAR (4)', 'description': 'Incremento Urgência'},
    'PA_TPUPS': {'type': 'CHAR (2)', 'description': 'Tipo de Estabelecimento'},
    'PA_TIPPRE': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'PA_MN_IND': {'type': 'CHAR (1)', 'description': 'Estabelecimento Mantido / Individual'},
    'PA_CNPJCPF': {'type': 'CHAR (14)', 'description': 'CNPJ do Estabelecimento executante'},
    'PA_CNPJMNT': {'type': 'CHAR (14)', 'description': 'CNPJ da Mantenedora do estabelecimento ou zeros, caso não a tenha'},
    'PA_CNPJ_CC': {'type': 'CHAR (14)', 'description': 'CNPJ do Órgão que recebeu pela produção por cessão de crédito ou zeros, caso não o tenha'},
    'PA_MVM': {'type': 'CHAR (6)', 'description': 'Data de Processamento / Movimento (AAAAMM)'},
    'PA_CMP': {'type': 'CHAR (6)', 'description': 'Data da Realização do Procedimento / Competência (AAAAMM)'},
    'PA_PROC_ID': {'type': 'CHAR (10)', 'description': 'Código do Procedimento Ambulatorial'},
    'PA_TPFIN': {'type': 'CHAR (2)', 'description': 'Tipo de Financiamento da produção'},
    'PA_SUBFIN': {'type': 'CHAR (4)', 'description': 'Subtipo de Financiamento da produção'},
    'PA_NIVCPL': {'type': 'CHAR (1)', 'description': 'Complexidade do Procedimento'},
    'PA_DOCORIG': {'type': 'CHAR (1)', 'description': 'Instrumento de Registro (conforme explicado na página 2)'},
    'PA_AUTORIZ': {'type': 'CHAR (13)', 'description': 'Número da APAC ou número de autorização do BPA-I, conforme o caso. No BPA-I, não é obrigatório, portanto, não é criticado. Lei de formação: UFAATsssssssd, onde: UF – Unid. da Federação, AA – ano, T – tipo, sssssss – sequencial, d – dígito'},
    'PA_CNSMED': {'type': 'CHAR (15)', 'description': 'Número do CNS (Cartão Nacional de Saúde) do profissional de saúde executante'},
    'PA_CBOCOD': {'type': 'CHAR (6)', 'description': 'Código da Ocupação do profissional na Classificação Brasileira de Ocupações8 (Ministério do Trabalho)'},
    'PA_MOTSAI': {'type': 'CHAR (2)', 'description': 'Motivo de saída ou zeros, caso não tenha'},
    'PA_OBITO': {'type': 'CHAR (1)', 'description': 'Indicador de Óbito (APAC)'},
    'PA_ENCERR': {'type': 'CHAR (1)', 'description': 'Indicador de Encerramento (APAC)'},
    'PA_PERMAN': {'type': 'CHAR (1)', 'description': 'Indicador de Permanência (APAC)'},
    'PA_ALTA': {'type': 'CHAR (1)', 'description': 'Indicador de Alta (APAC)'},
    'PA_TRANSF': {'type': 'CHAR (1)', 'description': 'Indicador de Transferência (APAC)'},
    'PA_CIDPRI': {'type': 'CHAR (4)', 'description': 'CID9 Principal (APAC ou BPA-I)'},
    'PA_CIDSEC': {'type': 'CHAR (4)', 'description': 'CID Secundário (APAC)'},
    'PA_CIDCAS': {'type': 'CHAR (4)', 'description': 'CID Causas Associadas (APAC)'},
    'PA_CATEND': {'type': 'CHAR (2)', 'description': 'Caráter de Atendimento (APAC ou BPA-I)'},
    'PA_IDADE': {'type': 'CHAR (3)', 'description': 'Idade do paciente em anos'},
    'IDADEMIN': {'type': 'CHAR (3)', 'description': 'Idade mínima do paciente para realização do procedimento'},
    'IDADEMAX': {'type': 'CHAR (3)', 'description': 'Idade máxima do paciente para realização do procedimento'},
    'PA_FLIDADE': {'type': 'CHAR (1)', 'description': 'Compatibilidade com a faixa de idade do procedimento (SIGTAP – Sistema de Gerenciamento da Tabela de Procedimentos do SUS): 0 = Idade não exigida; 1 = Idade compatível com o SIGTAP; 2 = Idade fora da faixa do SIGTAP; 3 = Idade inexistente; 4 = Idade EM BRANCO'},
    'PA_SEXO': {'type': 'CHAR (1)', 'description': 'Sexo do paciente'},
    'PA_RACACOR': {'type': 'CHAR (2)', 'description': 'Raça/Cor do paciente: 01 - Branca, 02 - Preta, 03 - Parda, 04 - Amarela, 05 - Indígena, 99 - Sem informação'},
    'PA_MUNPCN': {'type': 'CHAR (6)', 'description': 'Código da Unidade da Federação + Código do Município de residência do paciente ou do estabelecimento, caso não se tenha a identificação do paciente, o que ocorre no (BPA)'},
    'PA_QTDPRO': {'type': 'NUMERIC (11)', 'description': 'Quantidade Produzida (APRESENTADA)'},
    'PA_QTDAPR': {'type': 'NUMERIC (11)', 'description': 'Quantidade Aprovada do procedimento'},
    'PA_VALPRO': {'type': 'NUMERIC (20,2)', 'description': 'Valor Produzido (APRESENTADO)'},
    'PA_VALAPR': {'type': 'NUMERIC (20,2)', 'description': 'Valor Aprovado do procedimento'},
    'PA_UFDIF': {'type': 'CHAR (1)', 'description': 'Indica se a UF de residência do paciente é diferente da UF de localização do estabelecimento: 0 = mesma UF; 1 = UF diferente'},
    'PA_MNDIF': {'type': 'CHAR (1)', 'description': 'Indica se o município de residência do paciente é diferente do município de localização do estabelecimento: 0 = mesmo município; 1 = município diferente'},
    'PA_DIF_VAL': {'type': 'NUMERIC (20,2)', 'description': 'Diferença do Valor Unitário do procedimento praticado na Tabela Unificada com Valor Unitário praticado pelo Gestor da Produção, multiplicado pela Quantidade Aprovada'},
    'NU_VPA_TOT': {'type': 'NUMERIC (20,2)', 'description': 'Valor Unitário do Procedimento da Tabela VPA'},
    'NU_PA_TOT': {'type': 'NUMERIC (20,2)', 'description': 'Valor Unitário do Procedimento da Tabela SIGTAP'},
    'PA_INDICA': {'type': 'CHAR (1)', 'description': 'Indicativo de situação da produção produzida: 0 = não aprovado; 5 = aprovado total; 6 = aprovado parcial'},
    'PA_CODOCO': {'type': 'CHAR (1)', 'description': 'Código de Ocorrência'},
    'PA_FLQT': {'type': 'CHAR (1)', 'description': 'Indicador de erro de Quantidade Produzida'},
    'PA_FLER': {'type': 'CHAR (1)', 'description': 'Indicador de erro de corpo da APAC'},
    'PA_ETNIA': {'type': 'CHAR (4)', 'description': 'Etnia do paciente'},
    'PA_VL_CF': {'type': 'NUMERIC (20,2)', 'description': 'Valor do Complemento Federal'},
    'PA_VL_CL': {'type': 'NUMERIC (20,2)', 'description': 'Valor do Complemento Local'},
    'PA_VL_INC': {'type': 'NUMERIC (20,2)', 'description': 'Valor do Incremento'},
    'PA_SRC_C': {'type': 'CHAR(6)', 'description': 'Código do Serviço Especializado / Classificação CBO (de acordo com o CNES)'},
    'PA_INE': {'type': 'CHAR(10)', 'description': 'Código de Identificação Nacional de Equipes10, para registrar a atuação das equipes na execução de ações de saúde'},
    'PA_NAT_JUR': {'type': 'CHAR(4)', 'description': 'Código da Natureza Juridical'}
}


atd_dict = {
    'AP_MVM': {'type': 'CHAR (6)', 'description': 'Data de Processamento / Movimento (AAAAMM)'},
    'AP_CONDIC': {'type': 'CHAR (2)', 'description': 'Sigla do Tipo de Gestão no qual o Estado ou Município está habilitado'},
    'AP_GESTAO': {'type': 'CHAR (6)', 'description': 'Código da Unidade de Federação + Código Município de Gestão ou UF0000 se a Unidade está sob Gestão Estadual'},
    'AP_CODUNI': {'type': 'CHAR (7)', 'description': 'Código do Estabelecimento no CNES (Cadastro Nacional de Estabelecimentos de Saúde)'},
    'AP_AUTORIZ': {'type': 'CHAR (13)', 'description': 'Número da APAC. Lei de formação: UFAATsssssssd, onde UF – Unid. da Federação, AA – ano, T – tipo, sssssss – sequencial, d – dígito'},
    'AP_CMP': {'type': 'CHAR (6)', 'description': 'Data de Atendimento ao paciente / Competência (AAAAMM)'},
    'AP_PRIPAL': {'type': 'CHAR (10)', 'description': 'Procedimento Principal da APAC'},
    'AP_VL_AP': {'type': 'NUMERIC (20.2)', 'description': 'Valor Total da APAC Aprovado'},
    'AP_UFMUN': {'type': 'CHAR (6)', 'description': 'Código da Unidade da Federação + Código do Município do Estabelecimento'},
    'AP_TPUPS': {'type': 'CHAR (2)', 'description': 'Tipo de Estabelecimento'},
    'AP_TIPPRE': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'AP_MN_IND': {'type': 'CHAR (1)', 'description': 'Estabelecimento Mantido / Individual'},
    'AP_CNPJCPF': {'type': 'CHAR (14)', 'description': 'CNPJ do Estabelecimento executante'},
    'AP_CNPJMNT': {'type': 'CHAR (14)', 'description': 'CNPJ MANTENEDORA'},
    'AP_CNSPCN': {'type': 'CHAR (15)', 'description': 'Número do CNS (Cartão Nacional de Saúde) do paciente'},
    'AP_COIDADE': {'type': 'CHAR (1)', 'description': 'Código da Idade'},
    'AP_NUIDADE': {'type': 'CHAR (2)', 'description': 'Número da Idade'},
    'AP_SEXO': {'type': 'CHAR (1)', 'description': 'Sexo do paciente'},
    'AP_RACACOR': {'type': 'CHAR (2)', 'description': 'Raça/Cor do paciente: 01 - Branca, 02 - Preta, 03 - Parda, 04 - Amarela, 05 - Indígena, 99 - Sem informação'},
    'AP_MUNPCN': {'type': 'CHAR (6)', 'description': 'Código da UF + Código do Município de Residência do paciente'},
    'AP_UFNACIO': {'type': 'CHAR (3)', 'description': 'Nacionalidade do paciente'},
    'AP_CEPPCN': {'type': 'CHAR (8)', 'description': 'CEP do paciente'},
    'AP_UFDIF': {'type': 'CHAR (1)', 'description': 'Indica se a UF de residência do paciente é diferente da UF de localização do estabelecimento (N - não, S - sim)'},
    'AP_MNDIF': {'type': 'CHAR (1)', 'description': 'Indica se o município de residência do paciente é diferente do município de localização do estabelecimento (N - não, S - sim)'},
    'AP_DTINIC': {'type': 'CHAR (8)', 'description': 'Data de INÍCIO validade'},
    'AP_DTFIM': {'type': 'CHAR (8)', 'description': 'Data de FIM validade'},
    'AP_TPATEN': {'type': 'CHAR (2)', 'description': 'Tipo de Atendimento de APAC'},
    'AP_TPAPAC': {'type': 'CHAR (1)', 'description': 'Indica se a APAC é 1 – inicial, 2 – continuidade, 3 – única'},
    'AP_MOTSAI': {'type': 'CHAR (2)', 'description': 'Motivo de Saída e Permanência'},
    'AP_OBITO': {'type': 'CHAR (1)', 'description': 'Indicador de Óbito'},
    'AP_ENCERR': {'type': 'CHAR (1)', 'description': 'Indicador de Encerramento'},
    'AP_PERMAN': {'type': 'CHAR (1)', 'description': 'Indicador de Permanência'},
    'AP_ALTA': {'type': 'CHAR (1)', 'description': 'Indicador de Alta'},
    'AP_TRANSF': {'type': 'CHAR (1)', 'description': 'Indicador de Transferência'},
    'AP_DTOCOR': {'type': 'CHAR (8)', 'description': 'Data de Ocorrência que substitui a data de FIM de validade'},
    'AP_CODEMI': {'type': 'CHAR (10)', 'description': 'Código do Órgão emissor'},
    'AP_CATEND': {'type': 'CHAR (2)', 'description': 'Caráter do Atendimento'},
    'AP_APACANT': {'type': 'CHAR (13)', 'description': 'Número APAC Anterior'},
    'AP_UNISOL': {'type': 'CHAR (7)', 'description': 'Código CNES do Estabelecimento Solicitante'},
    'AP_DTSOLIC': {'type': 'CHAR(8)', 'description': 'Data da Solicitação'},
    'AP_DTAUT': {'type': 'CHAR(8)', 'description': 'Data da Autorização'},
    'AP_CIDCAS': {'type': 'CHAR (4)', 'description': 'CID Causas Associadas'},
    'AP_CIDPRI': {'type': 'CHAR (4)', 'description': 'CID Principal'},
    'AP_CIDSEC': {'type': 'CHAR (4)', 'description': 'CID Secundário'},
    'AP_ETNIA': {'type': 'CHAR (4)', 'description': 'Etnia do paciente'},
    'ATD_CARACT': {'type': 'CHAR (1)', 'description': 'Característica do tratamento'},
    'ATD_DTPDR': {'type': 'CHAR (8)', 'description': 'Data (AAAAMMDD) do início da primeira dialise'},
    'ATD_DTCLI': {'type': 'CHAR (8)', 'description': 'Data (AAAAMMDD) do início da dialise nesta clinica'},
    'ATD_ACEVAS': {'type': 'CHAR (1)', 'description': 'Acesso Vascular'},
    'ATD_MAISNE': {'type': 'CHAR (1)', 'description': 'Acompanhado há mais de um ano com nefrologia (S - Sim, N - Não, I - Ignorado)'},
    'ATD_SITINI': {'type': 'CHAR (1)', 'description': 'Situação Inicial'},
    'ATD_SITTRA': {'type': 'CHAR (1)', 'description': 'Situação de transplante (1 - Apto, 2 - Inapto, 3 - Recusa, 4 - N/A caso novo, com menos de 90 dias de tratamento)'},
    'ATD_SEAPTO': {'type': 'CHAR (1)', 'description': 'Se Apto a transplante (1 - Inscrito na CNCDO, 2 - Em processo de avaliação transplantante no centro transplantador, 3 - Sem encaminhamento, 4 - Aguardando agendamento de consulta no centro transplantador)'},
    'ATD_HB': {'type': 'CHAR (4)', 'description': 'HB (hemoglobina)'},
    'ATD_FOSFOR': {'type': 'CHAR (4)', 'description': 'Fósforo'},
    'ATD_KTVSEM': {'type': 'CHAR (4)', 'description': 'Kt/v Semanal'},
    'ATD_TRU': {'type': 'CHAR (4)', 'description': 'TRU (taxa de redução de ureia)'},
    'ATD_ALBUMI': {'type': 'CHAR (4)', 'description': 'Albumina'},
    'ATD_PTH': {'type': 'CHAR (4)', 'description': 'PTH (hormônio da paratireoide)'},
    'ATD_HIV': {'type': 'CHAR (1)', 'description': 'Indicativo de presença de anticorpos de HIV (P - Positivo; N - Negativo)'},
    'ATD_HCV': {'type': 'CHAR (1)', 'description': 'Indicativo de presença de anticorpos de HCV (P - Positivo; N - Negativo)'},
    'ATD_HBSAG': {'type': 'CHAR (1)', 'description': 'Indicativo de HBsAg (P - Positivo; N - Negativo)'},
    'ATD_INTERC': {'type': 'CHAR (1)', 'description': 'Usuário internado, com data de início no mês vigente, para tratamento de intercorrência clínica? (S – Sim, N - Não, I - Ignorado)'},
    'ATD_SEPERI': {'type': 'CHAR (1)', 'description': 'Se em Diálise Peritoneal, houve peritonite diagnosticada no mês vigente? (S - Sim, N - Não, I - Ignorado)'},
    'AP_NATJUR': {'type': 'CHAR (4)', 'description': 'Código da Natureza Jurídica'}
}


ps_dict = {
    'CNES_EXEC': {'type': 'CHAR (7)', 'description': 'Código do SCNES do Estabelecimento de Saúde'},
    'GESTAO': {'type': 'CHAR (6)', 'description': 'Unidade da Federação + Código do Município do Gestor, ou UF0000 se a Unidade está sob Gestão Estadual'},
    'CONDIC': {'type': 'CHAR (2)', 'description': 'Sigla do Tipo de Gestão no qual o Estado ou Município está habilitado'},
    'UFMUN': {'type': 'CHAR (6)', 'description': 'Unidade da Federação + município onde está localizado o Estabelecimento'},
    'TPUPS': {'type': 'CHAR (2)', 'description': 'Tipo de do Estabelecimento'},
    'TIPPRE': {'type': 'CHAR (2)', 'description': 'Tipo de Prestador'},
    'MN_IND': {'type': 'CHAR (1)', 'description': 'Estabelecimento Mantido / Individual'},
    'CNPJCPF': {'type': 'CHAR (14)', 'description': 'CNPJ do Estabelecimento executante'},
    'CNPJMNT': {'type': 'CHAR (14)', 'description': 'CNPJ da Mantenedora do Estabelecimento ou zeros, caso não a tenha'},
    'DT_PROCESS': {'type': 'CHAR (14)', 'description': 'Data de Processamento (AAAAMM)'},
    'DT_ATEND': {'type': 'CHAR (6)', 'description': 'Data do Atendimento (AAAAMM)'},
    'CNS_PAC': {'type': 'CHAR (15)', 'description': 'Número do CNS (Cartão Nacional de Saúde) do paciente (criptografia)'},
    'DTNASC': {'type': 'CHAR (8)', 'description': 'Data de nascimento do paciente'},
    'TPIDADEPAC': {'type': 'CHAR (1)', 'description': 'Tipo da Idade do paciente em anos, meses ou dias. Calculado a partir da data de nascimento'},
    'IDADEPAC': {'type': 'CHAR (2)', 'description': 'Idade do paciente'},
    'NACION_PAC': {'type': 'CHAR (2)', 'description': 'Nacionalidade do paciente'},
    'SEXOPAC': {'type': 'CHAR (1)', 'description': 'Sexo do paciente'},
    'RACACOR': {'type': 'CHAR (2)', 'description': 'Raça/Cor do paciente: 01 - Branca, 02 - Preta, 03 - Parda, 04 - Amarela, 05 - Indígena, 99 - Sem informação'},
    'ETNIA': {'type': 'CHAR (4)', 'description': 'Etnia do paciente (Caso seja da Raça/Cor Indígena)'},
    'MUNPAC': {'type': 'CHAR (6)', 'description': 'Unidade da Federação + município do município de residência do paciente'},
    'MOT_COB': {'type': 'CHAR (2)', 'description': 'Motivo de Saída/Permanência'},
    'DT_MOTCOB': {'type': 'CHAR (8)', 'description': 'Data da ocorrência no caso de alta, transferência ou óbito'},
    'CATEND': {'type': 'CHAR (2)', 'description': 'Caráter de Atendimento'},
    'CIDPRI': {'type': 'CHAR (4)', 'description': 'CID Principal'},
    'CIDASSOC': {'type': 'CHAR (4)', 'description': 'CID Causas Associadas'},
    'ORIGEM_PAC': {'type': 'CHAR (2)', 'description': 'Origem do paciente'},
    'DT_INICIO': {'type': 'CHAR (8)', 'description': 'Data de Início'},
    'DT_FIM': {'type': 'CHAR (8)', 'description': 'Data de Fim'},
    'COB_ESF': {'type': 'CHAR (1)', 'description': 'Indica se a região de atendimento do paciente tem cobertura de Estratégia Saúde da Família'},
    'CNES_ESF': {'type': 'CHAR (7)', 'description': 'Código do SCNES do Estabelecimento de Saúde Unidade da Saúde da Família da região'},
    'DESTINOPAC': {'type': 'CHAR (2)', 'description': 'Destino do paciente'},
    'PA_PROC_ID': {'type': 'CHAR(10)', 'description': 'Ação Realizada'},
    'QT_APRES': {'type': 'NUMERIC (11)', 'description': 'Quantidade Apresentada'},
    'QT_APROV': {'type': 'NUMERIC (11)', 'description': 'Quantidade Aprovada'},
    'SERV': {'type': 'CHAR (3)', 'description': 'Código do Serviço Especializado'},
    'CLASS': {'type': 'CHAR (3)', 'description': 'Código da Classificação do Serviço'},
    'SIT_RUA': {'type': 'CHAR (1)', 'description': 'Situação de Rua (S- SIM, N - NÃO)'},
    'TP_DROGA': {'type': 'CHAR (3)', 'description': 'TIPO DE DROGA (A - Álcool, C - Crack, O - Outros)'},
    'LOC_REALIZ': {'type': 'CHAR (1)', 'description': 'Local de Realização (C – CAPS, T - Território)'},
    'INICIO': {'type': 'CHAR (8)', 'description': 'Data de Início do Atendimento (DDMMAAAA)'},
    'FIM': {'type': 'CHAR (8)', 'description': 'Data de Fim do Atendimento (DDMMAAAA)'},
    'PERMANEN': {'type': 'CHAR (4)', 'description': 'Permanência em Atendimento'},
    'QTDATE': {'type': 'CHAR (4)', 'description': 'Quantidade de Atendimentos'},
    'QTDPCN': {'type': 'CHAR (4)', 'description': 'Quantidade de pacientes'}
}


sad_dict = {
    'CNES_EXEC': {'type': 'CHAR (7)', 'description': 'Código do SCNES do Estabelecimento de Saúde'},
    'GESTAO': {'type': 'CHAR (6)', 'description': 'Unidade da Federação + Código do Município do Gestor, ou UF0000 se a Unidade está sob Gestão Estadual'},
    'CONDIC': {'type': 'CHAR (2)', 'description': 'Sigla do Tipo de Gestão no qual o Estado ou Município está habilitado'},
    'UFMUN': {'type': 'CHAR (6)', 'description': 'Unidade da Federação + município onde está localizado o Estabelecimento'},
    'TPUPS': {'type': 'CHAR (2)', 'description': 'Tipo de do Estabelecimento'},
    'MN_IND': {'type': 'CHAR (1)', 'description': 'Estabelecimento Mantido / Individual'},
    'CNPJCPF': {'type': 'CHAR (14)', 'description': 'CNPJ do Estabelecimento executante'},
    'CNPJMNT': {'type': 'CHAR (14)', 'description': 'CNPJ da Mantenedora do Estabelecimento ou zeros, caso não a tenha'},
    'DT_PROCESS': {'type': 'CHAR (6)', 'description': 'Mês de Processamento (AAAAMM)'},
    'DT_ATEND': {'type': 'CHAR (6)', 'description': 'Mês do Atendimento (AAAAMM)'},
    'CNS_PAC': {'type': 'CHAR (15)', 'description': 'Número do CNS (Cartão Nacional de Saúde) do paciente (criptografia)'},
    'DTNASC': {'type': 'CHAR (8)', 'description': 'Data de nascimento do paciente'},
    'TPIDADEPAC': {'type': 'CHAR (1)', 'description': 'Tipo da Idade do paciente em anos, meses ou dias. Calculado a partir da data de nascimento'},
    'IDADEPAC': {'type': 'CHAR (2)', 'description': 'Idade do paciente'},
    'NACION_PAC': {'type': 'CHAR(2)', 'description': 'Nacionalidade do paciente'},
    'SEXOPAC': {'type': 'CHAR (1)', 'description': 'Sexo do paciente'},
    'RACACOR': {'type': 'CHAR (2)', 'description': 'Raça/Cor do paciente: 01 - Branca, 02 - Preta, 03 - Parda, 04 - Amarela, 05 - Indígena, 99 - Sem informação'},
    'ETNIA': {'type': 'CHAR (4)', 'description': 'Etnia do paciente (Caso seja da Raça/Cor Indígena)'},
    'MUNPAC': {'type': 'CHAR (6)', 'description': 'Unidade da Federação + município do município de residência do paciente'},
    'MOT_COB': {'type': 'CHAR (2)', 'description': 'Motivo de Saída/Permanência'},
    'DT_MOTCOB': {'type': 'CHAR (8)', 'description': 'Data da ocorrência no caso de alta, transferência ou óbito'},
    'CATEND': {'type': 'CHAR (2)', 'description': 'Caráter de Atendimento'},
    'CIDPRI': {'type': 'CHAR (4)', 'description': 'CID Principal'},
    'CIDASSOC': {'type': 'CHAR (4)', 'description': 'CID Causas Associadas'},
    'ORIGEM_PAC': {'type': 'CHAR (2)', 'description': 'Origem do paciente'},
    'DT_INÍCIO': {'type': 'CHAR (8)', 'description': 'Data de Início'},
    'DT_FIM': {'type': 'CHAR (8)', 'description': 'Data de Fim'},
    'COB_ESF': {'type': 'CHAR (1)', 'description': 'Indica se a região de atendimento do paciente tem cobertura de Estratégia Saúde da Família'},
    'CNES_ESF': {'type': 'CHAR (7)', 'description': 'Código do SCNES do Estabelecimento de Saúde Unidade da Saúde da Família da região'},
    'DESTINO_PAC': {'type': 'CHAR (2)', 'description': 'Destino do paciente'},
    'PA_PROC_ID': {'type': 'CHAR (10)', 'description': 'Código de Procedimento Ambulatorial'},
    'PA_QTDPRO': {'type': 'NUMERIC (11)', 'description': 'Quantidade Produzida (APRESENTADA)'},
    'PA_QTDAPR': {'type': 'NUMERIC (11)', 'description': 'Quantidade aprovada do procedimento'},
    'PA_SRV': {'type': 'CHAR (4)', 'description': 'Serviço Especializado'},
    'PA_CLAS_S': {'type': 'CHAR (4)', 'description': 'Classificação do Serviço'},
    'PA_EQUIPE': {'type': 'CHAR (12)', 'description': 'Código da Equipe (somente para o Instrumento de registro RAAS)'},
    'PA_TP_EQP': {'type': 'CHAR(2)', 'description': 'Tipo de Equipe (somente para o Instrumento de registro RAAS)'},
    'PA_CID': {'type': 'CHAR (4)', 'description': 'CID do Procedimento'},
    'DT_INICIO': {'type': 'CHAR (8)', 'description': 'Data de Início do Atendimento (DDMMAAAA)'},
    'DT_FIM': {'type': 'CHAR (8)', 'description': 'Data de Fim do Atendimento (DDMMAAAA)'},
    'PERMANENCIA': {'type': 'CHAR (4)', 'description': 'Permanência em Atendimento'},
    'QTDATE': {'type': 'CHAR (4)', 'description': 'Quantidade de Atendimentos'},
    'QTDPCN': {'type': 'CHAR (4)', 'description': 'Quantidade de pacientes'}
}