from django.db import models

class ABOSiasus(models.Model):
    ap_mvm= models.CharField(max_length=20, null=True)
    ap_condic= models.CharField(max_length=20, null=True)
    ap_gestao= models.CharField(max_length=20, null=True)
    ap_coduni= models.CharField(max_length=20, null=True)
    ap_autoriz= models.CharField(max_length=20, null=True)
    ap_cmp= models.CharField(max_length=20, null=True)
    ap_pripal= models.CharField(max_length=20, null=True)
    ap_vl_ap = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    ap_ufmun= models.CharField(max_length=20, null=True)
    ap_tpups= models.CharField(max_length=20, null=True)
    ap_tppre= models.CharField(max_length=20, null=True)
    ap_mn_ind= models.CharField(max_length=20, null=True)
    ap_cnpjcpf= models.CharField(max_length=20, null=True)
    ap_cnpjmnt= models.CharField(max_length=20, null=True)
    ap_cnspcn= models.CharField(max_length=20, null=True)
    ap_coidade= models.CharField(max_length=20, null=True)
    ap_nuidade= models.CharField(max_length=20, null=True)
    ap_sexo= models.CharField(max_length=20, null=True)
    ap_racacor= models.CharField(max_length=20, null=True)
    ap_munpcn= models.CharField(max_length=20, null=True)
    ap_ufnacio= models.CharField(max_length=20, null=True)
    ap_ceppcn= models.CharField(max_length=20, null=True)
    ap_ufdif= models.CharField(max_length=20, null=True)
    ap_mndif= models.CharField(max_length=20, null=True)
    ap_dtinic= models.CharField(max_length=20, null=True)
    ap_dtfim= models.CharField(max_length=20, null=True)
    ap_tpatend= models.CharField(max_length=20, null=True)
    ap_tpapac= models.CharField(max_length=20, null=True)
    ap_motsai= models.CharField(max_length=20, null=True)
    ap_obito= models.CharField(max_length=20, null=True)
    ap_encerr= models.CharField(max_length=20, null=True)
    ap_perman= models.CharField(max_length=20, null=True)
    ap_alta= models.CharField(max_length=20, null=True)
    ap_transf= models.CharField(max_length=20, null=True)
    ap_dtoocor= models.CharField(max_length=20, null=True)
    ap_codemi= models.CharField(max_length=20, null=True)
    ap_catend= models.CharField(max_length=20, null=True)
    ap_apacan= models.CharField(max_length=20, null=True)
    ap_unisol= models.CharField(max_length=20, null=True)
    ap_dtsolic= models.CharField(max_length=20, null=True)
    ap_dtaut= models.CharField(max_length=20, null=True)
    ap_cidcas= models.CharField(max_length=20, null=True)
    co_cidprim= models.CharField(max_length=20, null=True)
    co_cidsec= models.CharField(max_length=20, null=True)
    ap_etnia= models.CharField(max_length=20, null=True)
    ab_imc= models.CharField(max_length=20, null=True)
    ab_procaih= models.CharField(max_length=20, null=True)
    ab_dtcirur= models.CharField(max_length=20, null=True)
    ab_numaih= models.CharField(max_length=20, null=True)
    ab_prcaih2= models.CharField(max_length=20, null=True)
    ab_t_prc2= models.CharField(max_length=20, null=True)
    ab_prcaih3= models.CharField(max_length=20, null=True)
    ab_t_prc3= models.CharField(max_length=20, null=True)
    ab_prcaih4= models.CharField(max_length=20, null=True)
    ab_t_prc4= models.CharField(max_length=20, null=True)
    ab_prcaih5= models.CharField(max_length=20, null=True)
    ab_t_prc5= models.CharField(max_length=20, null=True)
    ab_prcaih6= models.CharField(max_length=20, null=True)
    ab_t_prc6= models.CharField(max_length=20, null=True)
    ab_numaih2= models.CharField(max_length=20, null=True)
    ab_dtcirg2= models.CharField(max_length=20, null=True)
    ab_mesacom= models.CharField(max_length=20, null=True)
    ab_anoacom= models.CharField(max_length=20, null=True)
    ab_pontbar= models.CharField(max_length=20, null=True)
    ab_tabbarr= models.CharField(max_length=20, null=True)
    ap_comorb= models.CharField(max_length=20, null=True)
    ap_cid_c1= models.CharField(max_length=20, null=True)
    ap_cid_c2= models.CharField(max_length=20, null=True)
    ap_cid_c3= models.CharField(max_length=20, null=True)
    ap_cid_c4= models.CharField(max_length=20, null=True)
    ap_cid_c5= models.CharField(max_length=20, null=True)
    ap_cid_co= models.CharField(max_length=20, null=True)
    ap_medicam= models.CharField(max_length=20, null=True)
    ap_polivit= models.CharField(max_length=20, null=True)
    ap_atv_fis= models.CharField(max_length=20, null=True)
    ap_reg_pes= models.CharField(max_length=20, null=True)
    ap_adesao= models.CharField(max_length=20, null=True)
    ap_natjur= models.CharField(max_length=20, null=True)
    uf = models.CharField(max_length=3, db_index=True)
    ano = models.CharField(max_length=4, db_index=True)
    mes = models.CharField(max_length=2, db_index=True)


    class Meta:
        db_table = 'abo_siasus'

        indexes = [
            models.Index(fields=['uf', 'ano', 'mes']),
            models.Index(fields=['uf', 'ano']),
            models.Index(fields=['uf', 'mes']),
            models.Index(fields=['mes', 'ano'])
        ]