from django.db import models

class PASiasus(models.Model):
    pa_coduni = models.CharField(max_length=25, null=True)
    pa_gestao = models.CharField(max_length=25, null=True)
    pa_condic = models.CharField(max_length=25, null=True)
    pa_ufmun = models.CharField(max_length=25, null=True)
    pa_regct = models.CharField(max_length=25, null=True)
    pa_incout = models.CharField(max_length=25, null=True)
    pa_incurg = models.CharField(max_length=25, null=True)
    pa_tpups = models.CharField(max_length=25, null=True)
    pa_tippre = models.CharField(max_length=25, null=True)
    pa_mn_ind = models.CharField(max_length=25, null=True)
    pa_cnpjcpf = models.CharField(max_length=25, null=True)
    pa_cnpjmnt = models.CharField(max_length=25, null=True)
    pa_cnpj_cc = models.CharField(max_length=25, null=True)
    pa_mvm = models.CharField(max_length=25, null=True)
    pa_cmp = models.CharField(max_length=25, null=True)
    pa_proc_id = models.CharField(max_length=25, null=True)
    pa_tpfin = models.CharField(max_length=25, null=True)
    pa_subfin = models.CharField(max_length=25, null=True)
    pa_nivcpl = models.CharField(max_length=25, null=True)
    pa_docorig = models.CharField(max_length=25, null=True)
    pa_autoriz = models.CharField(max_length=25, null=True)
    pa_cnsmed = models.CharField(max_length=25, null=True)
    pa_cbocod = models.CharField(max_length=25, null=True)
    pa_motsai = models.CharField(max_length=25, null=True)
    pa_obito = models.CharField(max_length=25, null=True)
    pa_encerr = models.CharField(max_length=25, null=True)
    pa_perman = models.CharField(max_length=25, null=True)
    pa_alta = models.CharField(max_length=25, null=True)
    pa_transf = models.CharField(max_length=25, null=True)
    pa_cidpri = models.CharField(max_length=25, null=True)
    pa_cidsec = models.CharField(max_length=25, null=True)
    pa_cidcas = models.CharField(max_length=25, null=True)
    pa_catend = models.CharField(max_length=25, null=True)
    pa_idade = models.CharField(max_length=25, null=True)
    idademin = models.CharField(max_length=25, null=True)
    idademax = models.CharField(max_length=25, null=True)
    pa_flidade = models.CharField(max_length=25, null=True)
    pa_sexo = models.CharField(max_length=25, null=True)
    pa_racacor = models.CharField(max_length=25, null=True)
    pa_munpcn = models.CharField(max_length=25, null=True)
    pa_qtdpro = models.IntegerField(null=True)
    pa_qtdapr = models.IntegerField(null=True)
    pa_valpro = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    pa_valapr = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    pa_ufdif = models.CharField(max_length=25, null=True)
    pa_mndif = models.CharField(max_length=25, null=True)
    pa_dif_val = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    nu_vpa_tot = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    nu_pa_tot = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    pa_indica = models.CharField(max_length=25, null=True)
    pa_codoco = models.CharField(max_length=25, null=True)
    pa_flqt = models.CharField(max_length=25, null=True)
    pa_fler = models.CharField(max_length=25, null=True)
    pa_etnia = models.CharField(max_length=25, null=True)
    pa_vl_cf = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    pa_vl_cl = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    pa_vl_inc = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    pa_srv_c = models.CharField(max_length=25, null=True)
    pa_ine = models.CharField(max_length=25, null=True)
    pa_nat_jur = models.CharField(max_length=25, null=True)
    uf = models.CharField(max_length=3, db_index=True)
    ano = models.CharField(max_length=4, db_index=True)
    mes = models.CharField(max_length=2, db_index=True)

    class Meta:
        db_table = 'pa_siasus'
        #ordering = ['-id']

        indexes = [
            models.Index(fields=['uf', 'ano', 'mes']),
            models.Index(fields=['uf', 'ano']),
            models.Index(fields=['uf', 'mes']),
            models.Index(fields=['mes', 'ano'])
        ]