from django.db import models

class DNEXSinasc(models.Model):
    origem = models.CharField(max_length=60, null=True)
    codestab = models.CharField(max_length=60, null=True)
    codmunnasc = models.CharField(max_length=60, null=True)
    locnasc = models.CharField(max_length=60, null=True)
    idademae = models.CharField(max_length=60, null=True)
    estcivmae = models.CharField(max_length=60, null=True)
    escmae = models.CharField(max_length=60, null=True)
    codocupmae = models.CharField(max_length=60, null=True)
    qtdfilvivo = models.CharField(max_length=60, null=True)
    qtdfilmort = models.CharField(max_length=60, null=True)
    codmunres = models.CharField(max_length=60, null=True)
    gestacao = models.CharField(max_length=60, null=True)
    gravidez = models.CharField(max_length=60, null=True)
    parto = models.CharField(max_length=60, null=True)
    consultas = models.CharField(max_length=60, null=True)
    dtnasc = models.CharField(max_length=60, null=True)
    horanasc = models.CharField(max_length=60, null=True)
    sexo = models.CharField(max_length=60, null=True)
    apgar1 = models.CharField(max_length=60, null=True)
    apgar5 = models.CharField(max_length=60, null=True)
    racacor = models.CharField(max_length=60, null=True)
    peso = models.CharField(max_length=60, null=True)
    idanomal = models.CharField(max_length=60, null=True)
    dtcadastro = models.CharField(max_length=60, null=True)
    codanomal = models.CharField(max_length=60, null=True)
    numerolote = models.CharField(max_length=60, null=True)
    versaosist = models.CharField(max_length=60, null=True)
    dtrecebim = models.CharField(max_length=60, null=True)
    difdata = models.CharField(max_length=60, null=True)
    dtrecoriga = models.CharField(max_length=60, null=True)
    naturalmae = models.CharField(max_length=60, null=True)
    codmunnatu = models.CharField(max_length=60, null=True)
    codufnatu = models.CharField(max_length=60, null=True)
    escmae2010 = models.CharField(max_length=60, null=True)
    seriescmae = models.CharField(max_length=60, null=True)
    dtnascmae = models.CharField(max_length=60, null=True)
    racacormae = models.CharField(max_length=60, null=True)
    qtdgestant = models.CharField(max_length=60, null=True)
    qtdpartnor = models.CharField(max_length=60, null=True)
    qtdpartces = models.CharField(max_length=60, null=True)
    idadepai = models.CharField(max_length=60, null=True)
    dtultmenst = models.CharField(max_length=60, null=True)
    semagestac = models.CharField(max_length=60, null=True)
    tpmetestim = models.CharField(max_length=60, null=True)
    consprenat = models.CharField(max_length=60, null=True)
    mesprenat = models.CharField(max_length=60, null=True)
    tpapresent = models.CharField(max_length=60, null=True)
    sttrabpart = models.CharField(max_length=60, null=True)
    stcesparto = models.CharField(max_length=60, null=True)
    tpnascassi = models.CharField(max_length=60, null=True)
    tpfuncresp = models.CharField(max_length=60, null=True)
    tpdocresp = models.CharField(max_length=60, null=True)
    dtdeclarac = models.CharField(max_length=60, null=True)
    escmaeagr1 = models.CharField(max_length=60, null=True)
    stdnepidem = models.CharField(max_length=60, null=True)
    stdnnova = models.CharField(max_length=60, null=True)
    codpaisres = models.CharField(max_length=60, null=True)
    tprobson = models.CharField(max_length=60, null=True)
    paridade = models.CharField(max_length=60, null=True)
    kotelchuck = models.CharField(max_length=60, null=True)
    contador = models.CharField(max_length=60, null=True)
    uf = models.CharField(max_length=3, db_index=True)
    ano = models.CharField(max_length=4, db_index=True)

    class Meta:
        db_table = 'dnex_sinasc'
        indexes = [
            models.Index(fields=['uf', 'ano'])
        ]