# Generated by Django 4.2.10 on 2024-03-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasus_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EQCnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(max_length=20, null=True)),
                ('codufmun', models.CharField(max_length=20, null=True)),
                ('regsaude', models.CharField(max_length=20, null=True)),
                ('micr_reg', models.CharField(max_length=20, null=True)),
                ('distrsan', models.CharField(max_length=20, null=True)),
                ('distradm', models.CharField(max_length=20, null=True)),
                ('tpgestao', models.CharField(max_length=20, null=True)),
                ('pf_pj', models.CharField(max_length=20, null=True)),
                ('cpf_cnpj', models.CharField(max_length=20, null=True)),
                ('niv_dep', models.CharField(max_length=20, null=True)),
                ('cnpj_man', models.CharField(max_length=20, null=True)),
                ('esfera_a', models.CharField(max_length=20, null=True)),
                ('atividad', models.CharField(max_length=20, null=True)),
                ('retencao', models.CharField(max_length=20, null=True)),
                ('natureza', models.CharField(max_length=20, null=True)),
                ('clientel', models.CharField(max_length=20, null=True)),
                ('tp_unid', models.CharField(max_length=20, null=True)),
                ('turno_at', models.CharField(max_length=20, null=True)),
                ('niv_hier', models.CharField(max_length=20, null=True)),
                ('terceiro', models.CharField(max_length=20, null=True)),
                ('tipequip', models.CharField(max_length=20, null=True)),
                ('codequip', models.CharField(max_length=20, null=True)),
                ('qt_exist', models.CharField(max_length=20, null=True)),
                ('qt_uso', models.CharField(max_length=20, null=True)),
                ('ind_sus', models.CharField(max_length=20, null=True)),
                ('ind_nsus', models.CharField(max_length=20, null=True)),
                ('competen', models.CharField(max_length=20, null=True)),
                ('nat_jur', models.CharField(max_length=20, null=True)),
                ('uf', models.CharField(db_index=True, max_length=3)),
                ('ano', models.CharField(db_index=True, max_length=4)),
                ('mes', models.CharField(db_index=True, max_length=2)),
            ],
            options={
                'db_table': 'eq_cnes',
                'indexes': [models.Index(fields=['uf', 'ano', 'mes'], name='eq_cnes_uf_c17f57_idx'), models.Index(fields=['uf', 'ano'], name='eq_cnes_uf_533f82_idx'), models.Index(fields=['uf', 'mes'], name='eq_cnes_uf_a9aa36_idx'), models.Index(fields=['mes', 'ano'], name='eq_cnes_mes_870d7c_idx')],
            },
        ),
    ]
