# Generated by Django 4.2.10 on 2024-03-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasus_api', '0002_eqcnes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMCnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(max_length=60, null=True)),
                ('codufmun', models.CharField(max_length=60, null=True)),
                ('regsaude', models.CharField(max_length=60, null=True)),
                ('micr_reg', models.CharField(max_length=60, null=True)),
                ('distrsan', models.CharField(max_length=60, null=True)),
                ('distradm', models.CharField(max_length=60, null=True)),
                ('tpgestao', models.CharField(max_length=60, null=True)),
                ('pf_pj', models.CharField(max_length=60, null=True)),
                ('cpf_cnpj', models.CharField(max_length=60, null=True)),
                ('niv_dep', models.CharField(max_length=60, null=True)),
                ('cnpj_man', models.CharField(max_length=60, null=True)),
                ('esfera_a', models.CharField(max_length=60, null=True)),
                ('retencao', models.CharField(max_length=60, null=True)),
                ('atividad', models.CharField(max_length=60, null=True)),
                ('natureza', models.CharField(max_length=60, null=True)),
                ('clientel', models.CharField(max_length=60, null=True)),
                ('tp_unid', models.CharField(max_length=60, null=True)),
                ('turno_at', models.CharField(max_length=60, null=True)),
                ('niv_hier', models.CharField(max_length=60, null=True)),
                ('terceiro', models.CharField(max_length=60, null=True)),
                ('cod_cep', models.CharField(max_length=60, null=True)),
                ('vinc_sus', models.CharField(max_length=60, null=True)),
                ('tp_prest', models.CharField(max_length=60, null=True)),
                ('sgruphab', models.CharField(max_length=60, null=True)),
                ('cmpt_ini', models.CharField(max_length=60, null=True)),
                ('cmpt_fim', models.CharField(max_length=60, null=True)),
                ('dtportar', models.CharField(max_length=60, null=True)),
                ('portaria', models.CharField(max_length=60, null=True)),
                ('maportar', models.CharField(max_length=60, null=True)),
                ('competen', models.CharField(max_length=60, null=True)),
                ('nat_jur', models.CharField(max_length=60, null=True)),
                ('uf', models.CharField(db_index=True, max_length=3)),
                ('ano', models.CharField(db_index=True, max_length=4)),
                ('mes', models.CharField(db_index=True, max_length=2)),
            ],
            options={
                'db_table': 'gm_cnes',
                'indexes': [models.Index(fields=['uf', 'ano', 'mes'], name='gm_cnes_uf_e98249_idx'), models.Index(fields=['uf', 'ano'], name='gm_cnes_uf_f8314d_idx'), models.Index(fields=['uf', 'mes'], name='gm_cnes_uf_d2938f_idx'), models.Index(fields=['mes', 'ano'], name='gm_cnes_mes_5d459b_idx')],
            },
        ),
    ]
