# Generated by Django 4.2.10 on 2024-03-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasus_api', '0003_gmcnes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HBCnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(max_length=55, null=True)),
                ('codufmun', models.CharField(max_length=55, null=True)),
                ('regsaude', models.CharField(max_length=55, null=True)),
                ('micr_reg', models.CharField(max_length=55, null=True)),
                ('distrsan', models.CharField(max_length=55, null=True)),
                ('distradm', models.CharField(max_length=55, null=True)),
                ('tpgestao', models.CharField(max_length=55, null=True)),
                ('pf_pj', models.CharField(max_length=55, null=True)),
                ('cpf_cnpj', models.CharField(max_length=55, null=True)),
                ('niv_dep', models.CharField(max_length=55, null=True)),
                ('cnpj_man', models.CharField(max_length=55, null=True)),
                ('esfera_a', models.CharField(max_length=55, null=True)),
                ('retencao', models.CharField(max_length=55, null=True)),
                ('atividad', models.CharField(max_length=55, null=True)),
                ('natureza', models.CharField(max_length=55, null=True)),
                ('clientel', models.CharField(max_length=55, null=True)),
                ('tp_unid', models.CharField(max_length=55, null=True)),
                ('turno_at', models.CharField(max_length=55, null=True)),
                ('niv_hier', models.CharField(max_length=55, null=True)),
                ('terceiro', models.CharField(max_length=55, null=True)),
                ('cod_cep', models.CharField(max_length=55, null=True)),
                ('vinc_sus', models.CharField(max_length=55, null=True)),
                ('tp_prest', models.CharField(max_length=55, null=True)),
                ('sgruphab', models.CharField(max_length=55, null=True)),
                ('cmpt_ini', models.CharField(max_length=55, null=True)),
                ('cmpt_fim', models.CharField(max_length=55, null=True)),
                ('dtportar', models.CharField(max_length=55, null=True)),
                ('portaria', models.CharField(max_length=55, null=True)),
                ('maportar', models.CharField(max_length=55, null=True)),
                ('nuleitos', models.IntegerField(null=True)),
                ('competen', models.CharField(max_length=6, null=True)),
                ('nat_jur', models.CharField(max_length=6, null=True)),
                ('uf', models.CharField(db_index=True, max_length=30)),
                ('ano', models.CharField(db_index=True, max_length=30)),
                ('mes', models.CharField(db_index=True, max_length=30)),
            ],
            options={
                'db_table': 'hb_cnes',
                'indexes': [models.Index(fields=['uf', 'ano', 'mes'], name='hb_cnes_uf_dd8350_idx'), models.Index(fields=['uf', 'ano'], name='hb_cnes_uf_1f57a1_idx'), models.Index(fields=['uf', 'mes'], name='hb_cnes_uf_53a19c_idx'), models.Index(fields=['mes', 'ano'], name='hb_cnes_mes_b6b185_idx')],
            },
        ),
    ]
