# Generated by Django 4.2.10 on 2024-05-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasus_api', '0007_hmsismama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hmsismama',
            old_name='Hicmicrca',
            new_name='hicmicrca',
        ),
    ]
