# Generated by Django 4.2.10 on 2024-04-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasus_api', '0008_adsiasus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMSiasus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_mvm', models.CharField(max_length=6, null=True)),
                ('ap_condic', models.CharField(max_length=2, null=True)),
                ('ap_gestao', models.CharField(max_length=6, null=True)),
                ('ap_coduni', models.CharField(max_length=7, null=True)),
                ('ap_autoriz', models.CharField(max_length=13, null=True)),
                ('ap_cmp', models.CharField(max_length=6, null=True)),
                ('ap_pripal', models.CharField(max_length=10, null=True)),
                ('ap_vl_ap', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('ap_ufmun', models.CharField(max_length=6, null=True)),
                ('ap_tpups', models.CharField(max_length=2, null=True)),
                ('ap_tippre', models.CharField(max_length=2, null=True)),
                ('ap_mn_ind', models.CharField(max_length=1, null=True)),
                ('ap_cnpjcpf', models.CharField(max_length=14, null=True)),
                ('ap_cnpjmnt', models.CharField(max_length=14, null=True)),
                ('ap_cnspcn', models.CharField(max_length=15, null=True)),
                ('ap_coidade', models.CharField(max_length=1, null=True)),
                ('ap_nuidade', models.CharField(max_length=2, null=True)),
                ('ap_sexo', models.CharField(max_length=1, null=True)),
                ('ap_racacor', models.CharField(max_length=2, null=True)),
                ('ap_munpcn', models.CharField(max_length=6, null=True)),
                ('ap_ufnacio', models.CharField(max_length=3, null=True)),
                ('ap_ceppcn', models.CharField(max_length=8, null=True)),
                ('ap_ufdif', models.CharField(max_length=2, null=True)),
                ('ap_mndif', models.CharField(max_length=2, null=True)),
                ('ap_dtinic', models.CharField(max_length=8, null=True)),
                ('ap_dtfim', models.CharField(max_length=8, null=True)),
                ('ap_tpaten', models.CharField(max_length=2, null=True)),
                ('ap_tpapac', models.CharField(max_length=1, null=True)),
                ('ap_motsai', models.CharField(max_length=2, null=True)),
                ('ap_obito', models.CharField(max_length=1, null=True)),
                ('ap_encerr', models.CharField(max_length=1, null=True)),
                ('ap_perman', models.CharField(max_length=1, null=True)),
                ('ap_alta', models.CharField(max_length=1, null=True)),
                ('ap_transf', models.CharField(max_length=1, null=True)),
                ('ap_dtocor', models.CharField(max_length=8, null=True)),
                ('ap_codemi', models.CharField(max_length=10, null=True)),
                ('ap_catend', models.CharField(max_length=2, null=True)),
                ('ap_apacant', models.CharField(max_length=13, null=True)),
                ('ap_unisol', models.CharField(max_length=7, null=True)),
                ('ap_dtsolic', models.CharField(max_length=8, null=True)),
                ('ap_dtaut', models.CharField(max_length=8, null=True)),
                ('ap_cidcas', models.CharField(max_length=4, null=True)),
                ('ap_cidpri', models.CharField(max_length=4, null=True)),
                ('ap_cidsec', models.CharField(max_length=4, null=True)),
                ('ap_etnia', models.CharField(max_length=4, null=True)),
                ('am_peso', models.CharField(max_length=3, null=True)),
                ('am_altura', models.CharField(max_length=3, null=True)),
                ('am_transpl', models.CharField(max_length=1, null=True)),
                ('am_qtdtran', models.CharField(max_length=2, null=True)),
                ('am_gestant', models.CharField(max_length=1, null=True)),
                ('ap_natjur', models.CharField(max_length=1, null=True)),
                ('uf', models.CharField(db_index=True, max_length=3)),
                ('ano', models.CharField(db_index=True, max_length=4)),
                ('mes', models.CharField(db_index=True, max_length=2)),
            ],
            options={
                'db_table': 'am_siasus',
                'indexes': [models.Index(fields=['uf', 'ano', 'mes'], name='am_siasus_uf_644be0_idx'), models.Index(fields=['uf', 'ano'], name='am_siasus_uf_3109b8_idx'), models.Index(fields=['uf', 'mes'], name='am_siasus_uf_5cc800_idx'), models.Index(fields=['mes', 'ano'], name='am_siasus_mes_203755_idx')],
            },
        ),
    ]
