# Generated by Django 4.2.10 on 2024-04-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasus_api', '0009_amsiasus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amsiasus',
            name='am_altura',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='am_gestant',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='am_peso',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='am_qtdtran',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='am_transpl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_alta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_apacant',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_autoriz',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_catend',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_ceppcn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_cidcas',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_cidpri',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_cidsec',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_cmp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_cnpjcpf',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_cnpjmnt',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_cnspcn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_codemi',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_coduni',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_coidade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_condic',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_dtaut',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_dtfim',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_dtinic',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_dtocor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_dtsolic',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_encerr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_etnia',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_gestao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_mn_ind',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_mndif',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_motsai',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_munpcn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_mvm',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_natjur',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_nuidade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_obito',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_perman',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_pripal',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_racacor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_sexo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_tippre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_tpapac',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_tpaten',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_tpups',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_transf',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_ufdif',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_ufmun',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_ufnacio',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amsiasus',
            name='ap_unisol',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
