# Generated by Django 4.2.10 on 2024-04-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasus_api', '0015_pssiasus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SADSiasus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes_exec', models.CharField(max_length=20, null=True)),
                ('gestao', models.CharField(max_length=20, null=True)),
                ('condic', models.CharField(max_length=20, null=True)),
                ('ufmun', models.CharField(max_length=20, null=True)),
                ('tpups', models.CharField(max_length=20, null=True)),
                ('mn_ind', models.CharField(max_length=20, null=True)),
                ('cnpjcpf', models.CharField(max_length=20, null=True)),
                ('cnpjmnt', models.CharField(max_length=20, null=True)),
                ('dt_process', models.CharField(max_length=20, null=True)),
                ('dt_atend', models.CharField(max_length=20, null=True)),
                ('cns_pac', models.CharField(max_length=20, null=True)),
                ('dtnasc', models.CharField(max_length=20, null=True)),
                ('tpidadepac', models.CharField(max_length=20, null=True)),
                ('idadepac', models.CharField(max_length=20, null=True)),
                ('nacion_pac', models.CharField(max_length=20, null=True)),
                ('sexopac', models.CharField(max_length=20, null=True)),
                ('racacor', models.CharField(max_length=20, null=True)),
                ('etnia', models.CharField(max_length=20, null=True)),
                ('munpac', models.CharField(max_length=20, null=True)),
                ('mot_cob', models.CharField(max_length=20, null=True)),
                ('dt_motcob', models.CharField(max_length=20, null=True)),
                ('catend', models.CharField(max_length=20, null=True)),
                ('cidpri', models.CharField(max_length=20, null=True)),
                ('cidassoc', models.CharField(max_length=20, null=True)),
                ('origem_pac', models.CharField(max_length=20, null=True)),
                ('dt_inicio', models.CharField(max_length=20, null=True)),
                ('dt_fim', models.CharField(max_length=20, null=True)),
                ('cob_esf', models.CharField(max_length=20, null=True)),
                ('cnes_esf', models.CharField(max_length=20, null=True)),
                ('destinopac', models.CharField(max_length=20, null=True)),
                ('pa_proc_id', models.CharField(max_length=20, null=True)),
                ('pa_qtdpro', models.IntegerField(null=True)),
                ('pa_qtdapr', models.IntegerField(null=True)),
                ('pa_srv', models.CharField(max_length=20, null=True)),
                ('pa_class_s', models.CharField(max_length=20, null=True)),
                ('pa_equipe', models.CharField(max_length=20, null=True)),
                ('pa_tp_eqp', models.CharField(max_length=20, null=True)),
                ('pa_cid', models.CharField(max_length=20, null=True)),
                ('inicio', models.CharField(max_length=20, null=True)),
                ('fim', models.CharField(max_length=20, null=True)),
                ('permanen', models.CharField(max_length=20, null=True)),
                ('qtdate', models.CharField(max_length=20, null=True)),
                ('qtdpcn', models.CharField(max_length=20, null=True)),
                ('co_ine', models.CharField(max_length=20, null=True)),
                ('nat_jur', models.CharField(max_length=20, null=True)),
                ('uf', models.CharField(db_index=True, max_length=3)),
                ('ano', models.CharField(db_index=True, max_length=4)),
                ('mes', models.CharField(db_index=True, max_length=2)),
            ],
            options={
                'db_table': 'sad_siasus',
                'indexes': [models.Index(fields=['uf', 'ano', 'mes'], name='sad_siasus_uf_1cc645_idx'), models.Index(fields=['uf', 'ano'], name='sad_siasus_uf_fed0cb_idx'), models.Index(fields=['uf', 'mes'], name='sad_siasus_uf_242061_idx'), models.Index(fields=['mes', 'ano'], name='sad_siasus_mes_f452f0_idx')],
            },
        ),
    ]
