# Generated by Django 4.2.10 on 2024-04-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasus_api', '0016_sadsiasus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERSihsus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.CharField(max_length=25, null=True)),
                ('remessa', models.CharField(max_length=25, null=True)),
                ('cnes', models.CharField(max_length=25, null=True)),
                ('aih', models.CharField(max_length=25, null=True)),
                ('dt_inter', models.CharField(max_length=25, null=True)),
                ('dt_saida', models.CharField(max_length=25, null=True)),
                ('mun_mov', models.CharField(max_length=25, null=True)),
                ('uf_zi', models.CharField(max_length=25, null=True)),
                ('mun_res', models.CharField(max_length=25, null=True)),
                ('uf_res', models.CharField(max_length=25, null=True)),
                ('co_erro', models.CharField(max_length=25, null=True)),
                ('uf', models.CharField(db_index=True, max_length=3)),
                ('ano', models.CharField(db_index=True, max_length=4)),
                ('mes', models.CharField(db_index=True, max_length=2)),
            ],
            options={
                'db_table': 'er_sihsus',
                'indexes': [models.Index(fields=['uf', 'ano', 'mes'], name='er_sihsus_uf_44ad3b_idx'), models.Index(fields=['uf', 'ano'], name='er_sihsus_uf_b6eb51_idx'), models.Index(fields=['uf', 'mes'], name='er_sihsus_uf_2fdd3c_idx'), models.Index(fields=['mes', 'ano'], name='er_sihsus_mes_69236e_idx')],
            },
        ),
    ]
