# Generated by Django 4.2.10 on 2024-04-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasus_api', '0019_rjsihsus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPSihsus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_gestor', models.CharField(max_length=65, null=True)),
                ('sp_uf', models.CharField(max_length=65, null=True)),
                ('sp_aa', models.CharField(max_length=65, null=True)),
                ('sp_mm', models.CharField(max_length=65, null=True)),
                ('sp_cnes', models.CharField(max_length=65, null=True)),
                ('sp_naih', models.CharField(max_length=65, null=True)),
                ('sp_procrea', models.CharField(max_length=65, null=True)),
                ('sp_dtinter', models.CharField(max_length=65, null=True)),
                ('sp_dtsaida', models.CharField(max_length=65, null=True)),
                ('sp_num_pr', models.CharField(max_length=65, null=True)),
                ('sp_tipo', models.CharField(max_length=65, null=True)),
                ('sp_cpfcgc', models.CharField(max_length=65, null=True)),
                ('sp_atoprof', models.CharField(max_length=65, null=True)),
                ('sp_tp_ato', models.CharField(max_length=65, null=True)),
                ('sp_qtd_ato', models.IntegerField(null=True)),
                ('sp_ptsp', models.CharField(max_length=65, null=True)),
                ('sp_nf', models.CharField(max_length=65, null=True)),
                ('sp_valato', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('sp_m_hosp', models.CharField(max_length=65, null=True)),
                ('sp_m_pac', models.CharField(max_length=65, null=True)),
                ('sp_des_hos', models.CharField(max_length=65, null=True)),
                ('sp_des_pac', models.CharField(max_length=65, null=True)),
                ('sp_complex', models.CharField(max_length=65, null=True)),
                ('sp_financ', models.CharField(max_length=65, null=True)),
                ('sp_co_faec', models.CharField(max_length=65, null=True)),
                ('sp_pf_cbo', models.CharField(max_length=65, null=True)),
                ('sp_pf_doc', models.CharField(max_length=65, null=True)),
                ('sp_pj_doc', models.CharField(max_length=65, null=True)),
                ('in_tp_val', models.CharField(max_length=65, null=True)),
                ('sequencia', models.CharField(max_length=65, null=True)),
                ('serv_cla', models.CharField(max_length=65, null=True)),
                ('sp_cidpri', models.CharField(max_length=65, null=True)),
                ('sp_cidsec', models.CharField(max_length=65, null=True)),
                ('sp_qt_proc', models.IntegerField(null=True)),
                ('sp_u_aih', models.CharField(max_length=65, null=True)),
                ('remessa', models.CharField(max_length=65, null=True)),
                ('uf', models.CharField(db_index=True, max_length=3)),
                ('ano', models.CharField(db_index=True, max_length=4)),
                ('mes', models.CharField(db_index=True, max_length=2)),
            ],
            options={
                'db_table': 'sp_sihsus',
                'indexes': [models.Index(fields=['uf', 'ano', 'mes'], name='sp_sihsus_uf_47759e_idx'), models.Index(fields=['uf', 'ano'], name='sp_sihsus_uf_85198f_idx'), models.Index(fields=['uf', 'mes'], name='sp_sihsus_uf_679a77_idx'), models.Index(fields=['mes', 'ano'], name='sp_sihsus_mes_4dcadc_idx')],
            },
        ),
    ]
