from django.db import models

class CMSismama(models.Model):
    co_pac_uf = models.CharField(max_length=60, null=True)
    co_us_uf = models.CharField(max_length=60, null=True)
    co_pac_ibg = models.CharField(max_length=60, null=True)
    co_us_ibge = models.CharField(max_length=60, null=True)
    co_us = models.CharField(max_length=60, null=True)
    co_cnes = models.CharField(max_length=60, null=True)
    prestuf = models.CharField(max_length=60, null=True)
    regus = models.CharField(max_length=60, null=True)
    regresid = models.CharField(max_length=60, null=True)
    reglab = models.CharField(max_length=60, null=True)
    ano_comp = models.CharField(max_length=60, null=True)
    prestmun = models.CharField(max_length=60, null=True)
    dt_id_comp = models.CharField(max_length=60, null=True)
    co_fx_etar = models.CharField(max_length=60, null=True)
    co_pac_esc = models.CharField(max_length=60, null=True)
    co_pac_sex = models.CharField(max_length=60, null=True)
    co_pac_rac = models.CharField(max_length=60, null=True)
    canmpacanc = models.CharField(max_length=60, null=True)
    co_cli_des = models.CharField(max_length=60, null=True)
    co_cli_nod = models.CharField(max_length=60, null=True)
    cclimatmam = models.CharField(max_length=60, null=True)
    cclimatdpc = models.CharField(max_length=60, null=True)
    dintcoleta = models.CharField(max_length=60, null=True)
    dintresult = models.CharField(max_length=60, null=True)
    dinttempex = models.CharField(max_length=60, null=True)
    co_res_ade = models.CharField(max_length=60, null=True)
    presulpaaf = models.CharField(max_length=60, null=True)
    cresbenig = models.CharField(max_length=60, null=True)
    cresmaliin = models.CharField(max_length=60, null=True)
    cressusmal = models.CharField(max_length=60, null=True)
    cresposmal = models.CharField(max_length=60, null=True)
    cresderpap = models.CharField(max_length=60, null=True)
    quantexame = models.CharField(max_length=60, null=True)
    pbenmastit = models.CharField(max_length=60, null=True)
    pbenabsuba = models.CharField(max_length=60, null=True)
    pbenfibroa = models.CharField(max_length=60, null=True)
    pbennecgor = models.CharField(max_length=60, null=True)
    pbencondfi = models.CharField(max_length=60, null=True)
    pbenlesepi = models.CharField(max_length=60, null=True)
    pbenoutras = models.CharField(max_length=60, null=True)
    pmalintump = models.CharField(max_length=60, null=True)
    pmalintumf = models.CharField(max_length=60, null=True)
    pmalinoutr = models.CharField(max_length=60, null=True)
    psuslejpca = models.CharField(max_length=60, null=True)
    psusoutros = models.CharField(max_length=60, null=True)
    pposmacduc = models.CharField(max_length=60, null=True)
    pposmaclob = models.CharField(max_length=60, null=True)
    pposmacout = models.CharField(max_length=60, null=True)
    dematacelu = models.CharField(max_length=60, null=True)
    denegmalig = models.CharField(max_length=60, null=True)
    demaliindt = models.CharField(max_length=60, null=True)
    deposmalig = models.CharField(max_length=60, null=True)
    delesmalig = models.CharField(max_length=60, null=True)
    deprocinfl = models.CharField(max_length=60, null=True)
    uf = models.CharField(max_length=3, db_index=True)
    ano = models.CharField(max_length=4, db_index=True)
    mes = models.CharField(max_length=2, db_index=True)

    class Meta:
        db_table = 'cm_sismama'
        indexes = [
            models.Index(fields=['uf', 'ano', 'mes']),
            models.Index(fields=['uf', 'ano']),
            models.Index(fields=['uf', 'mes']),
            models.Index(fields=['mes', 'ano'])
        ]