from django.db import models

class HMSismama(models.Model):
    co_pac_uf = models.CharField(max_length=60, null=True)
    co_us_uf = models.CharField(max_length=60, null=True)
    co_pac_ibg = models.CharField(max_length=60, null=True)
    co_us_ibge = models.CharField(max_length=60, null=True)
    co_us = models.CharField(max_length=60, null=True)
    co_cnes = models.CharField(max_length=60, null=True)
    prestuf = models.CharField(max_length=60, null=True)
    prestmun = models.CharField(max_length=60, null=True)
    regus = models.CharField(max_length=60, null=True)
    regresid = models.CharField(max_length=60, null=True)
    reglab = models.CharField(max_length=60, null=True)
    ano_comp = models.CharField(max_length=60, null=True)
    dt_id_comp = models.CharField(max_length=60, null=True)
    co_fx_etar = models.CharField(max_length=60, null=True)
    co_pac_esc = models.CharField(max_length=60, null=True)
    co_pac_sex = models.CharField(max_length=60, null=True)
    co_pac_rac = models.CharField(max_length=60, null=True)
    cclitpexa = models.CharField(max_length=60, null=True)
    cclitant = models.CharField(max_length=60, null=True)
    cclidiagim = models.CharField(max_length=60, null=True)
    ccliloca = models.CharField(max_length=60, null=True)
    chislinfco = models.CharField(max_length=60, null=True)
    chisreces = models.CharField(max_length=60, null=True)
    chisrecpr = models.CharField(max_length=60, null=True)
    c_cli_tcan = models.CharField(max_length=60, null=True)
    c_cli_dete = models.CharField(max_length=60, null=True)
    co_cli_mam = models.CharField(max_length=60, null=True)
    co_cli_tam = models.CharField(max_length=60, null=True)
    co_tam_tum = models.CharField(max_length=60, null=True)
    c_cli_linf = models.CharField(max_length=60, null=True)
    cclimatpro = models.CharField(max_length=60, null=True)
    dintcoleta = models.CharField(max_length=60, null=True)
    dintresult = models.CharField(max_length=60, null=True)
    dinttempex = models.CharField(max_length=60, null=True)
    cresprocir = models.CharField(max_length=60, null=True)
    co_res_ade = models.CharField(max_length=60, null=True)
    hicmicrca = models.CharField(max_length=60, null=True)
    c_neo_mali = models.CharField(max_length=60, null=True)
    co_his_gra = models.CharField(max_length=60, null=True)
    co_his_mar = models.CharField(max_length=60, null=True)
    quantexame = models.CharField(max_length=60, null=True)
    lesbenigin = models.CharField(max_length=60, null=True)
    cneomalig = models.CharField(max_length=60, null=True)
    cbenhipsat = models.CharField(max_length=60, null=True)
    cbenhipcat = models.CharField(max_length=60, null=True)
    cbenlobcat = models.CharField(max_length=60, null=True)
    cbenadenos = models.CharField(max_length=60, null=True)
    cbenesdero = models.CharField(max_length=60, null=True)
    cbenfibroc = models.CharField(max_length=60, null=True)
    cbenfibroa = models.CharField(max_length=60, null=True)
    cbensolita = models.CharField(max_length=60, null=True)
    cbenmulti = models.CharField(max_length=60, null=True)
    cbenflorid = models.CharField(max_length=60, null=True)
    cbenmastit = models.CharField(max_length=60, null=True)
    cbenoutros = models.CharField(max_length=60, null=True)
    uf = models.CharField(max_length=3, db_index=True)
    ano = models.CharField(max_length=4, db_index=True)
    mes = models.CharField(max_length=2, db_index=True)

    class Meta:
        db_table = 'hm_sismama'
        indexes = [
            models.Index(fields=['uf', 'ano', 'mes']),
            models.Index(fields=['uf', 'ano']),
            models.Index(fields=['uf', 'mes']),
            models.Index(fields=['mes', 'ano'])
        ]